apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "fleet-lite-app.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  data:
  - remoteRef:
      key: {{ .Release.Namespace }}/fleet-lite-app/db_user
    secretKey: DB_USER
  - remoteRef:
      key: {{ .Release.Namespace }}/fleet-lite-app/db_password
    secretKey: DB_PASSWORD
  - remoteRef:
      key: {{ .Release.Namespace }}/fleet-lite-app/db_host
    secretKey: DB_HOST
  - remoteRef:
      key: {{ .Release.Namespace }}/fleet-lite-app/dimo_auth_private_key
    secretKey: DIMO_AUTH_PRIVATE_KEY
  - remoteRef:
      key: {{ .Release.Namespace }}/fleet-lite-app/postmark_server_token
    secretKey: POSTMARK_SERVER_TOKEN

  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager-secret-store
  target:
    name: {{ include "fleet-lite-app.fullname" . }}-secret
    template:
      metadata: {}
