// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	FleetGroups        string
	Geofences          string
	Invitations        string
	TenantUsers        string
	Tenants            string
	VehicleFavorites   string
	VehicleFleetGroups string
	VehicleGeofences   string
	Vehicles           string
}{
	FleetGroups:        "fleet_groups",
	Geofences:          "geofences",
	Invitations:        "invitations",
	TenantUsers:        "tenant_users",
	Tenants:            "tenants",
	VehicleFavorites:   "vehicle_favorites",
	VehicleFleetGroups: "vehicle_fleet_groups",
	VehicleGeofences:   "vehicle_geofences",
	Vehicles:           "vehicles",
}
