// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	FleetGroups          string
	GeofencePasses       string
	GeofenceScanCoverage string
	Geofences            string
	Invitations          string
	TenantUsers          string
	Tenants              string
	UserPreferences      string
	VehicleFavorites     string
	VehicleFleetGroups   string
	VehicleGeofences     string
	VehicleTcoSettings   string
	Vehicles             string
}{
	FleetGroups:          "fleet_groups",
	GeofencePasses:       "geofence_passes",
	GeofenceScanCoverage: "geofence_scan_coverage",
	Geofences:            "geofences",
	Invitations:          "invitations",
	TenantUsers:          "tenant_users",
	Tenants:              "tenants",
	UserPreferences:      "user_preferences",
	VehicleFavorites:     "vehicle_favorites",
	VehicleFleetGroups:   "vehicle_fleet_groups",
	VehicleGeofences:     "vehicle_geofences",
	VehicleTcoSettings:   "vehicle_tco_settings",
	Vehicles:             "vehicles",
}
