// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// ChargingSession is an object representing the database table.
type ChargingSession struct {
	TenantID       string       `boil:"tenant_id" json:"tenant_id" toml:"tenant_id" yaml:"tenant_id"`
	TokenID        int64        `boil:"token_id" json:"token_id" toml:"token_id" yaml:"token_id"`
	StartedAt      time.Time    `boil:"started_at" json:"started_at" toml:"started_at" yaml:"started_at"`
	EndedAt        time.Time    `boil:"ended_at" json:"ended_at" toml:"ended_at" yaml:"ended_at"`
	AddedEnergyKWH null.Float64 `boil:"added_energy_kwh" json:"added_energy_kwh,omitempty" toml:"added_energy_kwh" yaml:"added_energy_kwh,omitempty"`
	AvgPowerKW     null.Float64 `boil:"avg_power_kw" json:"avg_power_kw,omitempty" toml:"avg_power_kw" yaml:"avg_power_kw,omitempty"`
	SocStartPCT    null.Float64 `boil:"soc_start_pct" json:"soc_start_pct,omitempty" toml:"soc_start_pct" yaml:"soc_start_pct,omitempty"`
	SocEndPCT      null.Float64 `boil:"soc_end_pct" json:"soc_end_pct,omitempty" toml:"soc_end_pct" yaml:"soc_end_pct,omitempty"`
	Lat            null.Float64 `boil:"lat" json:"lat,omitempty" toml:"lat" yaml:"lat,omitempty"`
	LNG            null.Float64 `boil:"lng" json:"lng,omitempty" toml:"lng" yaml:"lng,omitempty"`
	CreatedAt      time.Time    `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *chargingSessionR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L chargingSessionL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ChargingSessionColumns = struct {
	TenantID       string
	TokenID        string
	StartedAt      string
	EndedAt        string
	AddedEnergyKWH string
	AvgPowerKW     string
	SocStartPCT    string
	SocEndPCT      string
	Lat            string
	LNG            string
	CreatedAt      string
}{
	TenantID:       "tenant_id",
	TokenID:        "token_id",
	StartedAt:      "started_at",
	EndedAt:        "ended_at",
	AddedEnergyKWH: "added_energy_kwh",
	AvgPowerKW:     "avg_power_kw",
	SocStartPCT:    "soc_start_pct",
	SocEndPCT:      "soc_end_pct",
	Lat:            "lat",
	LNG:            "lng",
	CreatedAt:      "created_at",
}

var ChargingSessionTableColumns = struct {
	TenantID       string
	TokenID        string
	StartedAt      string
	EndedAt        string
	AddedEnergyKWH string
	AvgPowerKW     string
	SocStartPCT    string
	SocEndPCT      string
	Lat            string
	LNG            string
	CreatedAt      string
}{
	TenantID:       "charging_sessions.tenant_id",
	TokenID:        "charging_sessions.token_id",
	StartedAt:      "charging_sessions.started_at",
	EndedAt:        "charging_sessions.ended_at",
	AddedEnergyKWH: "charging_sessions.added_energy_kwh",
	AvgPowerKW:     "charging_sessions.avg_power_kw",
	SocStartPCT:    "charging_sessions.soc_start_pct",
	SocEndPCT:      "charging_sessions.soc_end_pct",
	Lat:            "charging_sessions.lat",
	LNG:            "charging_sessions.lng",
	CreatedAt:      "charging_sessions.created_at",
}

// Generated where

type whereHelpernull_Float64 struct{ field string }

func (w whereHelpernull_Float64) EQ(x null.Float64) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Float64) NEQ(x null.Float64) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Float64) LT(x null.Float64) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Float64) LTE(x null.Float64) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Float64) GT(x null.Float64) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Float64) GTE(x null.Float64) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelpernull_Float64) IN(slice []float64) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelpernull_Float64) NIN(slice []float64) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

func (w whereHelpernull_Float64) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Float64) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

type whereHelperint struct{ field string }

func (w whereHelperint) EQ(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint) NEQ(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint) LT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint) LTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint) GT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint) GTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint) IN(slice []int) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint) NIN(slice []int) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

var ChargingSessionWhere = struct {
	TenantID       whereHelperstring
	TokenID        whereHelperint64
	StartedAt      whereHelpertime_Time
	EndedAt        whereHelpertime_Time
	AddedEnergyKWH whereHelpernull_Float64
	AvgPowerKW     whereHelpernull_Float64
	SocStartPCT    whereHelpernull_Float64
	SocEndPCT      whereHelpernull_Float64
	Lat            whereHelpernull_Float64
	LNG            whereHelpernull_Float64
	CreatedAt      whereHelpertime_Time
}{
	TenantID:       whereHelperstring{field: "\"charging_sessions\".\"tenant_id\""},
	TokenID:        whereHelperint64{field: "\"charging_sessions\".\"token_id\""},
	StartedAt:      whereHelpertime_Time{field: "\"charging_sessions\".\"started_at\""},
	EndedAt:        whereHelpertime_Time{field: "\"charging_sessions\".\"ended_at\""},
	AddedEnergyKWH: whereHelpernull_Float64{field: "\"charging_sessions\".\"added_energy_kwh\""},
	AvgPowerKW:     whereHelpernull_Float64{field: "\"charging_sessions\".\"avg_power_kw\""},
	SocStartPCT:    whereHelpernull_Float64{field: "\"charging_sessions\".\"soc_start_pct\""},
	SocEndPCT:      whereHelpernull_Float64{field: "\"charging_sessions\".\"soc_end_pct\""},
	Lat:            whereHelpernull_Float64{field: "\"charging_sessions\".\"lat\""},
	LNG:            whereHelpernull_Float64{field: "\"charging_sessions\".\"lng\""},
	CreatedAt:      whereHelpertime_Time{field: "\"charging_sessions\".\"created_at\""},
}

// ChargingSessionRels is where relationship names are stored.
var ChargingSessionRels = struct {
}{}

// chargingSessionR is where relationships are stored.
type chargingSessionR struct {
}

// NewStruct creates a new relationship struct
func (*chargingSessionR) NewStruct() *chargingSessionR {
	return &chargingSessionR{}
}

// chargingSessionL is where Load methods for each relationship are stored.
type chargingSessionL struct{}

var (
	chargingSessionAllColumns            = []string{"tenant_id", "token_id", "started_at", "ended_at", "added_energy_kwh", "avg_power_kw", "soc_start_pct", "soc_end_pct", "lat", "lng", "created_at"}
	chargingSessionColumnsWithoutDefault = []string{"tenant_id", "token_id", "started_at", "ended_at"}
	chargingSessionColumnsWithDefault    = []string{"added_energy_kwh", "avg_power_kw", "soc_start_pct", "soc_end_pct", "lat", "lng", "created_at"}
	chargingSessionPrimaryKeyColumns     = []string{"tenant_id", "token_id", "started_at"}
	chargingSessionGeneratedColumns      = []string{}
)

type (
	// ChargingSessionSlice is an alias for a slice of pointers to ChargingSession.
	// This should almost always be used instead of []ChargingSession.
	ChargingSessionSlice []*ChargingSession
	// ChargingSessionHook is the signature for custom ChargingSession hook methods
	ChargingSessionHook func(context.Context, boil.ContextExecutor, *ChargingSession) error

	chargingSessionQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	chargingSessionType                 = reflect.TypeOf(&ChargingSession{})
	chargingSessionMapping              = queries.MakeStructMapping(chargingSessionType)
	chargingSessionPrimaryKeyMapping, _ = queries.BindMapping(chargingSessionType, chargingSessionMapping, chargingSessionPrimaryKeyColumns)
	chargingSessionInsertCacheMut       sync.RWMutex
	chargingSessionInsertCache          = make(map[string]insertCache)
	chargingSessionUpdateCacheMut       sync.RWMutex
	chargingSessionUpdateCache          = make(map[string]updateCache)
	chargingSessionUpsertCacheMut       sync.RWMutex
	chargingSessionUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var chargingSessionAfterSelectMu sync.Mutex
var chargingSessionAfterSelectHooks []ChargingSessionHook

var chargingSessionBeforeInsertMu sync.Mutex
var chargingSessionBeforeInsertHooks []ChargingSessionHook
var chargingSessionAfterInsertMu sync.Mutex
var chargingSessionAfterInsertHooks []ChargingSessionHook

var chargingSessionBeforeUpdateMu sync.Mutex
var chargingSessionBeforeUpdateHooks []ChargingSessionHook
var chargingSessionAfterUpdateMu sync.Mutex
var chargingSessionAfterUpdateHooks []ChargingSessionHook

var chargingSessionBeforeDeleteMu sync.Mutex
var chargingSessionBeforeDeleteHooks []ChargingSessionHook
var chargingSessionAfterDeleteMu sync.Mutex
var chargingSessionAfterDeleteHooks []ChargingSessionHook

var chargingSessionBeforeUpsertMu sync.Mutex
var chargingSessionBeforeUpsertHooks []ChargingSessionHook
var chargingSessionAfterUpsertMu sync.Mutex
var chargingSessionAfterUpsertHooks []ChargingSessionHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *ChargingSession) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range chargingSessionAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *ChargingSession) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range chargingSessionBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *ChargingSession) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range chargingSessionAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *ChargingSession) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range chargingSessionBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *ChargingSession) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range chargingSessionAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *ChargingSession) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range chargingSessionBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *ChargingSession) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range chargingSessionAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *ChargingSession) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range chargingSessionBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *ChargingSession) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range chargingSessionAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddChargingSessionHook registers your hook function for all future operations.
func AddChargingSessionHook(hookPoint boil.HookPoint, chargingSessionHook ChargingSessionHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		chargingSessionAfterSelectMu.Lock()
		chargingSessionAfterSelectHooks = append(chargingSessionAfterSelectHooks, chargingSessionHook)
		chargingSessionAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		chargingSessionBeforeInsertMu.Lock()
		chargingSessionBeforeInsertHooks = append(chargingSessionBeforeInsertHooks, chargingSessionHook)
		chargingSessionBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		chargingSessionAfterInsertMu.Lock()
		chargingSessionAfterInsertHooks = append(chargingSessionAfterInsertHooks, chargingSessionHook)
		chargingSessionAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		chargingSessionBeforeUpdateMu.Lock()
		chargingSessionBeforeUpdateHooks = append(chargingSessionBeforeUpdateHooks, chargingSessionHook)
		chargingSessionBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		chargingSessionAfterUpdateMu.Lock()
		chargingSessionAfterUpdateHooks = append(chargingSessionAfterUpdateHooks, chargingSessionHook)
		chargingSessionAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		chargingSessionBeforeDeleteMu.Lock()
		chargingSessionBeforeDeleteHooks = append(chargingSessionBeforeDeleteHooks, chargingSessionHook)
		chargingSessionBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		chargingSessionAfterDeleteMu.Lock()
		chargingSessionAfterDeleteHooks = append(chargingSessionAfterDeleteHooks, chargingSessionHook)
		chargingSessionAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		chargingSessionBeforeUpsertMu.Lock()
		chargingSessionBeforeUpsertHooks = append(chargingSessionBeforeUpsertHooks, chargingSessionHook)
		chargingSessionBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		chargingSessionAfterUpsertMu.Lock()
		chargingSessionAfterUpsertHooks = append(chargingSessionAfterUpsertHooks, chargingSessionHook)
		chargingSessionAfterUpsertMu.Unlock()
	}
}

// One returns a single chargingSession record from the query.
func (q chargingSessionQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ChargingSession, error) {
	o := &ChargingSession{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for charging_sessions")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all ChargingSession records from the query.
func (q chargingSessionQuery) All(ctx context.Context, exec boil.ContextExecutor) (ChargingSessionSlice, error) {
	var o []*ChargingSession

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to ChargingSession slice")
	}

	if len(chargingSessionAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all ChargingSession records in the query.
func (q chargingSessionQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count charging_sessions rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q chargingSessionQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if charging_sessions exists")
	}

	return count > 0, nil
}

// ChargingSessions retrieves all the records using an executor.
func ChargingSessions(mods ...qm.QueryMod) chargingSessionQuery {
	mods = append(mods, qm.From("\"charging_sessions\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"charging_sessions\".*"})
	}

	return chargingSessionQuery{q}
}

// FindChargingSession retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindChargingSession(ctx context.Context, exec boil.ContextExecutor, tenantID string, tokenID int64, startedAt time.Time, selectCols ...string) (*ChargingSession, error) {
	chargingSessionObj := &ChargingSession{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"charging_sessions\" where \"tenant_id\"=$1 AND \"token_id\"=$2 AND \"started_at\"=$3", sel,
	)

	q := queries.Raw(query, tenantID, tokenID, startedAt)

	err := q.Bind(ctx, exec, chargingSessionObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from charging_sessions")
	}

	if err = chargingSessionObj.doAfterSelectHooks(ctx, exec); err != nil {
		return chargingSessionObj, err
	}

	return chargingSessionObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ChargingSession) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no charging_sessions provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(chargingSessionColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	chargingSessionInsertCacheMut.RLock()
	cache, cached := chargingSessionInsertCache[key]
	chargingSessionInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			chargingSessionAllColumns,
			chargingSessionColumnsWithDefault,
			chargingSessionColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(chargingSessionType, chargingSessionMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(chargingSessionType, chargingSessionMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"charging_sessions\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"charging_sessions\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into charging_sessions")
	}

	if !cached {
		chargingSessionInsertCacheMut.Lock()
		chargingSessionInsertCache[key] = cache
		chargingSessionInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the ChargingSession.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ChargingSession) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	chargingSessionUpdateCacheMut.RLock()
	cache, cached := chargingSessionUpdateCache[key]
	chargingSessionUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			chargingSessionAllColumns,
			chargingSessionPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update charging_sessions, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"charging_sessions\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, chargingSessionPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(chargingSessionType, chargingSessionMapping, append(wl, chargingSessionPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update charging_sessions row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for charging_sessions")
	}

	if !cached {
		chargingSessionUpdateCacheMut.Lock()
		chargingSessionUpdateCache[key] = cache
		chargingSessionUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q chargingSessionQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for charging_sessions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for charging_sessions")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ChargingSessionSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), chargingSessionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"charging_sessions\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, chargingSessionPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in chargingSession slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all chargingSession")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ChargingSession) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no charging_sessions provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(chargingSessionColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	chargingSessionUpsertCacheMut.RLock()
	cache, cached := chargingSessionUpsertCache[key]
	chargingSessionUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			chargingSessionAllColumns,
			chargingSessionColumnsWithDefault,
			chargingSessionColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			chargingSessionAllColumns,
			chargingSessionPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert charging_sessions, could not build update column list")
		}

		ret := strmangle.SetComplement(chargingSessionAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(chargingSessionPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert charging_sessions, could not build conflict column list")
			}

			conflict = make([]string, len(chargingSessionPrimaryKeyColumns))
			copy(conflict, chargingSessionPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"charging_sessions\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(chargingSessionType, chargingSessionMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(chargingSessionType, chargingSessionMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert charging_sessions")
	}

	if !cached {
		chargingSessionUpsertCacheMut.Lock()
		chargingSessionUpsertCache[key] = cache
		chargingSessionUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single ChargingSession record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ChargingSession) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no ChargingSession provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), chargingSessionPrimaryKeyMapping)
	sql := "DELETE FROM \"charging_sessions\" WHERE \"tenant_id\"=$1 AND \"token_id\"=$2 AND \"started_at\"=$3"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from charging_sessions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for charging_sessions")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q chargingSessionQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no chargingSessionQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from charging_sessions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for charging_sessions")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ChargingSessionSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(chargingSessionBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), chargingSessionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"charging_sessions\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, chargingSessionPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from chargingSession slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for charging_sessions")
	}

	if len(chargingSessionAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ChargingSession) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindChargingSession(ctx, exec, o.TenantID, o.TokenID, o.StartedAt)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ChargingSessionSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ChargingSessionSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), chargingSessionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"charging_sessions\".* FROM \"charging_sessions\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, chargingSessionPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in ChargingSessionSlice")
	}

	*o = slice

	return nil
}

// ChargingSessionExists checks if the ChargingSession row exists.
func ChargingSessionExists(ctx context.Context, exec boil.ContextExecutor, tenantID string, tokenID int64, startedAt time.Time) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"charging_sessions\" where \"tenant_id\"=$1 AND \"token_id\"=$2 AND \"started_at\"=$3 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, tenantID, tokenID, startedAt)
	}
	row := exec.QueryRowContext(ctx, sql, tenantID, tokenID, startedAt)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if charging_sessions exists")
	}

	return exists, nil
}

// Exists checks if the ChargingSession row exists.
func (o *ChargingSession) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ChargingSessionExists(ctx, exec, o.TenantID, o.TokenID, o.StartedAt)
}
