// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// ChargingScanCoverage is an object representing the database table.
type ChargingScanCoverage struct {
	TenantID    string    `boil:"tenant_id" json:"tenant_id" toml:"tenant_id" yaml:"tenant_id"`
	TokenID     int64     `boil:"token_id" json:"token_id" toml:"token_id" yaml:"token_id"`
	ScannedFrom time.Time `boil:"scanned_from" json:"scanned_from" toml:"scanned_from" yaml:"scanned_from"`
	ScannedTo   time.Time `boil:"scanned_to" json:"scanned_to" toml:"scanned_to" yaml:"scanned_to"`
	CreatedAt   time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *chargingScanCoverageR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L chargingScanCoverageL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ChargingScanCoverageColumns = struct {
	TenantID    string
	TokenID     string
	ScannedFrom string
	ScannedTo   string
	CreatedAt   string
}{
	TenantID:    "tenant_id",
	TokenID:     "token_id",
	ScannedFrom: "scanned_from",
	ScannedTo:   "scanned_to",
	CreatedAt:   "created_at",
}

var ChargingScanCoverageTableColumns = struct {
	TenantID    string
	TokenID     string
	ScannedFrom string
	ScannedTo   string
	CreatedAt   string
}{
	TenantID:    "charging_scan_coverage.tenant_id",
	TokenID:     "charging_scan_coverage.token_id",
	ScannedFrom: "charging_scan_coverage.scanned_from",
	ScannedTo:   "charging_scan_coverage.scanned_to",
	CreatedAt:   "charging_scan_coverage.created_at",
}

// Generated where

type whereHelperstring struct{ field string }

func (w whereHelperstring) EQ(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperstring) NEQ(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperstring) LT(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperstring) LTE(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperstring) GT(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperstring) GTE(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperstring) LIKE(x string) qm.QueryMod    { return qm.Where(w.field+" LIKE ?", x) }
func (w whereHelperstring) NLIKE(x string) qm.QueryMod   { return qm.Where(w.field+" NOT LIKE ?", x) }
func (w whereHelperstring) ILIKE(x string) qm.QueryMod   { return qm.Where(w.field+" ILIKE ?", x) }
func (w whereHelperstring) NILIKE(x string) qm.QueryMod  { return qm.Where(w.field+" NOT ILIKE ?", x) }
func (w whereHelperstring) SIMILAR(x string) qm.QueryMod { return qm.Where(w.field+" SIMILAR TO ?", x) }
func (w whereHelperstring) NSIMILAR(x string) qm.QueryMod {
	return qm.Where(w.field+" NOT SIMILAR TO ?", x)
}
func (w whereHelperstring) IN(slice []string) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperstring) NIN(slice []string) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelperint64 struct{ field string }

func (w whereHelperint64) EQ(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint64) NEQ(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint64) LT(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint64) LTE(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint64) GT(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint64) GTE(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint64) IN(slice []int64) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint64) NIN(slice []int64) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelpertime_Time struct{ field string }

func (w whereHelpertime_Time) EQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertime_Time) NEQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertime_Time) LT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertime_Time) LTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertime_Time) GT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertime_Time) GTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

var ChargingScanCoverageWhere = struct {
	TenantID    whereHelperstring
	TokenID     whereHelperint64
	ScannedFrom whereHelpertime_Time
	ScannedTo   whereHelpertime_Time
	CreatedAt   whereHelpertime_Time
}{
	TenantID:    whereHelperstring{field: "\"fleet_lite_app\".\"charging_scan_coverage\".\"tenant_id\""},
	TokenID:     whereHelperint64{field: "\"fleet_lite_app\".\"charging_scan_coverage\".\"token_id\""},
	ScannedFrom: whereHelpertime_Time{field: "\"fleet_lite_app\".\"charging_scan_coverage\".\"scanned_from\""},
	ScannedTo:   whereHelpertime_Time{field: "\"fleet_lite_app\".\"charging_scan_coverage\".\"scanned_to\""},
	CreatedAt:   whereHelpertime_Time{field: "\"fleet_lite_app\".\"charging_scan_coverage\".\"created_at\""},
}

// ChargingScanCoverageRels is where relationship names are stored.
var ChargingScanCoverageRels = struct {
}{}

// chargingScanCoverageR is where relationships are stored.
type chargingScanCoverageR struct {
}

// NewStruct creates a new relationship struct
func (*chargingScanCoverageR) NewStruct() *chargingScanCoverageR {
	return &chargingScanCoverageR{}
}

// chargingScanCoverageL is where Load methods for each relationship are stored.
type chargingScanCoverageL struct{}

var (
	chargingScanCoverageAllColumns            = []string{"tenant_id", "token_id", "scanned_from", "scanned_to", "created_at"}
	chargingScanCoverageColumnsWithoutDefault = []string{"tenant_id", "token_id", "scanned_from", "scanned_to"}
	chargingScanCoverageColumnsWithDefault    = []string{"created_at"}
	chargingScanCoveragePrimaryKeyColumns     = []string{"tenant_id", "token_id", "scanned_from"}
	chargingScanCoverageGeneratedColumns      = []string{}
)

type (
	// ChargingScanCoverageSlice is an alias for a slice of pointers to ChargingScanCoverage.
	// This should almost always be used instead of []ChargingScanCoverage.
	ChargingScanCoverageSlice []*ChargingScanCoverage
	// ChargingScanCoverageHook is the signature for custom ChargingScanCoverage hook methods
	ChargingScanCoverageHook func(context.Context, boil.ContextExecutor, *ChargingScanCoverage) error

	chargingScanCoverageQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	chargingScanCoverageType                 = reflect.TypeOf(&ChargingScanCoverage{})
	chargingScanCoverageMapping              = queries.MakeStructMapping(chargingScanCoverageType)
	chargingScanCoveragePrimaryKeyMapping, _ = queries.BindMapping(chargingScanCoverageType, chargingScanCoverageMapping, chargingScanCoveragePrimaryKeyColumns)
	chargingScanCoverageInsertCacheMut       sync.RWMutex
	chargingScanCoverageInsertCache          = make(map[string]insertCache)
	chargingScanCoverageUpdateCacheMut       sync.RWMutex
	chargingScanCoverageUpdateCache          = make(map[string]updateCache)
	chargingScanCoverageUpsertCacheMut       sync.RWMutex
	chargingScanCoverageUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var chargingScanCoverageAfterSelectMu sync.Mutex
var chargingScanCoverageAfterSelectHooks []ChargingScanCoverageHook

var chargingScanCoverageBeforeInsertMu sync.Mutex
var chargingScanCoverageBeforeInsertHooks []ChargingScanCoverageHook
var chargingScanCoverageAfterInsertMu sync.Mutex
var chargingScanCoverageAfterInsertHooks []ChargingScanCoverageHook

var chargingScanCoverageBeforeUpdateMu sync.Mutex
var chargingScanCoverageBeforeUpdateHooks []ChargingScanCoverageHook
var chargingScanCoverageAfterUpdateMu sync.Mutex
var chargingScanCoverageAfterUpdateHooks []ChargingScanCoverageHook

var chargingScanCoverageBeforeDeleteMu sync.Mutex
var chargingScanCoverageBeforeDeleteHooks []ChargingScanCoverageHook
var chargingScanCoverageAfterDeleteMu sync.Mutex
var chargingScanCoverageAfterDeleteHooks []ChargingScanCoverageHook

var chargingScanCoverageBeforeUpsertMu sync.Mutex
var chargingScanCoverageBeforeUpsertHooks []ChargingScanCoverageHook
var chargingScanCoverageAfterUpsertMu sync.Mutex
var chargingScanCoverageAfterUpsertHooks []ChargingScanCoverageHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *ChargingScanCoverage) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range chargingScanCoverageAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *ChargingScanCoverage) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range chargingScanCoverageBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *ChargingScanCoverage) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range chargingScanCoverageAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *ChargingScanCoverage) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range chargingScanCoverageBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *ChargingScanCoverage) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range chargingScanCoverageAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *ChargingScanCoverage) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range chargingScanCoverageBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *ChargingScanCoverage) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range chargingScanCoverageAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *ChargingScanCoverage) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range chargingScanCoverageBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *ChargingScanCoverage) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range chargingScanCoverageAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddChargingScanCoverageHook registers your hook function for all future operations.
func AddChargingScanCoverageHook(hookPoint boil.HookPoint, chargingScanCoverageHook ChargingScanCoverageHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		chargingScanCoverageAfterSelectMu.Lock()
		chargingScanCoverageAfterSelectHooks = append(chargingScanCoverageAfterSelectHooks, chargingScanCoverageHook)
		chargingScanCoverageAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		chargingScanCoverageBeforeInsertMu.Lock()
		chargingScanCoverageBeforeInsertHooks = append(chargingScanCoverageBeforeInsertHooks, chargingScanCoverageHook)
		chargingScanCoverageBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		chargingScanCoverageAfterInsertMu.Lock()
		chargingScanCoverageAfterInsertHooks = append(chargingScanCoverageAfterInsertHooks, chargingScanCoverageHook)
		chargingScanCoverageAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		chargingScanCoverageBeforeUpdateMu.Lock()
		chargingScanCoverageBeforeUpdateHooks = append(chargingScanCoverageBeforeUpdateHooks, chargingScanCoverageHook)
		chargingScanCoverageBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		chargingScanCoverageAfterUpdateMu.Lock()
		chargingScanCoverageAfterUpdateHooks = append(chargingScanCoverageAfterUpdateHooks, chargingScanCoverageHook)
		chargingScanCoverageAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		chargingScanCoverageBeforeDeleteMu.Lock()
		chargingScanCoverageBeforeDeleteHooks = append(chargingScanCoverageBeforeDeleteHooks, chargingScanCoverageHook)
		chargingScanCoverageBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		chargingScanCoverageAfterDeleteMu.Lock()
		chargingScanCoverageAfterDeleteHooks = append(chargingScanCoverageAfterDeleteHooks, chargingScanCoverageHook)
		chargingScanCoverageAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		chargingScanCoverageBeforeUpsertMu.Lock()
		chargingScanCoverageBeforeUpsertHooks = append(chargingScanCoverageBeforeUpsertHooks, chargingScanCoverageHook)
		chargingScanCoverageBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		chargingScanCoverageAfterUpsertMu.Lock()
		chargingScanCoverageAfterUpsertHooks = append(chargingScanCoverageAfterUpsertHooks, chargingScanCoverageHook)
		chargingScanCoverageAfterUpsertMu.Unlock()
	}
}

// One returns a single chargingScanCoverage record from the query.
func (q chargingScanCoverageQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ChargingScanCoverage, error) {
	o := &ChargingScanCoverage{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for charging_scan_coverage")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all ChargingScanCoverage records from the query.
func (q chargingScanCoverageQuery) All(ctx context.Context, exec boil.ContextExecutor) (ChargingScanCoverageSlice, error) {
	var o []*ChargingScanCoverage

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to ChargingScanCoverage slice")
	}

	if len(chargingScanCoverageAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all ChargingScanCoverage records in the query.
func (q chargingScanCoverageQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count charging_scan_coverage rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q chargingScanCoverageQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if charging_scan_coverage exists")
	}

	return count > 0, nil
}

// ChargingScanCoverages retrieves all the records using an executor.
func ChargingScanCoverages(mods ...qm.QueryMod) chargingScanCoverageQuery {
	mods = append(mods, qm.From("\"fleet_lite_app\".\"charging_scan_coverage\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"fleet_lite_app\".\"charging_scan_coverage\".*"})
	}

	return chargingScanCoverageQuery{q}
}

// FindChargingScanCoverage retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindChargingScanCoverage(ctx context.Context, exec boil.ContextExecutor, tenantID string, tokenID int64, scannedFrom time.Time, selectCols ...string) (*ChargingScanCoverage, error) {
	chargingScanCoverageObj := &ChargingScanCoverage{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"fleet_lite_app\".\"charging_scan_coverage\" where \"tenant_id\"=$1 AND \"token_id\"=$2 AND \"scanned_from\"=$3", sel,
	)

	q := queries.Raw(query, tenantID, tokenID, scannedFrom)

	err := q.Bind(ctx, exec, chargingScanCoverageObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from charging_scan_coverage")
	}

	if err = chargingScanCoverageObj.doAfterSelectHooks(ctx, exec); err != nil {
		return chargingScanCoverageObj, err
	}

	return chargingScanCoverageObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ChargingScanCoverage) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no charging_scan_coverage provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(chargingScanCoverageColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	chargingScanCoverageInsertCacheMut.RLock()
	cache, cached := chargingScanCoverageInsertCache[key]
	chargingScanCoverageInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			chargingScanCoverageAllColumns,
			chargingScanCoverageColumnsWithDefault,
			chargingScanCoverageColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(chargingScanCoverageType, chargingScanCoverageMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(chargingScanCoverageType, chargingScanCoverageMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"fleet_lite_app\".\"charging_scan_coverage\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"fleet_lite_app\".\"charging_scan_coverage\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into charging_scan_coverage")
	}

	if !cached {
		chargingScanCoverageInsertCacheMut.Lock()
		chargingScanCoverageInsertCache[key] = cache
		chargingScanCoverageInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the ChargingScanCoverage.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ChargingScanCoverage) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	chargingScanCoverageUpdateCacheMut.RLock()
	cache, cached := chargingScanCoverageUpdateCache[key]
	chargingScanCoverageUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			chargingScanCoverageAllColumns,
			chargingScanCoveragePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update charging_scan_coverage, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"fleet_lite_app\".\"charging_scan_coverage\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, chargingScanCoveragePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(chargingScanCoverageType, chargingScanCoverageMapping, append(wl, chargingScanCoveragePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update charging_scan_coverage row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for charging_scan_coverage")
	}

	if !cached {
		chargingScanCoverageUpdateCacheMut.Lock()
		chargingScanCoverageUpdateCache[key] = cache
		chargingScanCoverageUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q chargingScanCoverageQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for charging_scan_coverage")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for charging_scan_coverage")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ChargingScanCoverageSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), chargingScanCoveragePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"fleet_lite_app\".\"charging_scan_coverage\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, chargingScanCoveragePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in chargingScanCoverage slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all chargingScanCoverage")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ChargingScanCoverage) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no charging_scan_coverage provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(chargingScanCoverageColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	chargingScanCoverageUpsertCacheMut.RLock()
	cache, cached := chargingScanCoverageUpsertCache[key]
	chargingScanCoverageUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			chargingScanCoverageAllColumns,
			chargingScanCoverageColumnsWithDefault,
			chargingScanCoverageColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			chargingScanCoverageAllColumns,
			chargingScanCoveragePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert charging_scan_coverage, could not build update column list")
		}

		ret := strmangle.SetComplement(chargingScanCoverageAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(chargingScanCoveragePrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert charging_scan_coverage, could not build conflict column list")
			}

			conflict = make([]string, len(chargingScanCoveragePrimaryKeyColumns))
			copy(conflict, chargingScanCoveragePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"fleet_lite_app\".\"charging_scan_coverage\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(chargingScanCoverageType, chargingScanCoverageMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(chargingScanCoverageType, chargingScanCoverageMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert charging_scan_coverage")
	}

	if !cached {
		chargingScanCoverageUpsertCacheMut.Lock()
		chargingScanCoverageUpsertCache[key] = cache
		chargingScanCoverageUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single ChargingScanCoverage record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ChargingScanCoverage) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no ChargingScanCoverage provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), chargingScanCoveragePrimaryKeyMapping)
	sql := "DELETE FROM \"fleet_lite_app\".\"charging_scan_coverage\" WHERE \"tenant_id\"=$1 AND \"token_id\"=$2 AND \"scanned_from\"=$3"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from charging_scan_coverage")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for charging_scan_coverage")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q chargingScanCoverageQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no chargingScanCoverageQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from charging_scan_coverage")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for charging_scan_coverage")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ChargingScanCoverageSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(chargingScanCoverageBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), chargingScanCoveragePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"fleet_lite_app\".\"charging_scan_coverage\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, chargingScanCoveragePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from chargingScanCoverage slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for charging_scan_coverage")
	}

	if len(chargingScanCoverageAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ChargingScanCoverage) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindChargingScanCoverage(ctx, exec, o.TenantID, o.TokenID, o.ScannedFrom)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ChargingScanCoverageSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ChargingScanCoverageSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), chargingScanCoveragePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"fleet_lite_app\".\"charging_scan_coverage\".* FROM \"fleet_lite_app\".\"charging_scan_coverage\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, chargingScanCoveragePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in ChargingScanCoverageSlice")
	}

	*o = slice

	return nil
}

// ChargingScanCoverageExists checks if the ChargingScanCoverage row exists.
func ChargingScanCoverageExists(ctx context.Context, exec boil.ContextExecutor, tenantID string, tokenID int64, scannedFrom time.Time) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"fleet_lite_app\".\"charging_scan_coverage\" where \"tenant_id\"=$1 AND \"token_id\"=$2 AND \"scanned_from\"=$3 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, tenantID, tokenID, scannedFrom)
	}
	row := exec.QueryRowContext(ctx, sql, tenantID, tokenID, scannedFrom)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if charging_scan_coverage exists")
	}

	return exists, nil
}

// Exists checks if the ChargingScanCoverage row exists.
func (o *ChargingScanCoverage) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ChargingScanCoverageExists(ctx, exec, o.TenantID, o.TokenID, o.ScannedFrom)
}
