// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// FleetGroup is an object representing the database table.
type FleetGroup struct {
	ID        string    `boil:"id" json:"id" toml:"id" yaml:"id"`
	Name      string    `boil:"name" json:"name" toml:"name" yaml:"name"`
	Color     string    `boil:"color" json:"color" toml:"color" yaml:"color"`
	TenantID  string    `boil:"tenant_id" json:"tenant_id" toml:"tenant_id" yaml:"tenant_id"`
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *fleetGroupR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L fleetGroupL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var FleetGroupColumns = struct {
	ID        string
	Name      string
	Color     string
	TenantID  string
	CreatedAt string
	UpdatedAt string
}{
	ID:        "id",
	Name:      "name",
	Color:     "color",
	TenantID:  "tenant_id",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

var FleetGroupTableColumns = struct {
	ID        string
	Name      string
	Color     string
	TenantID  string
	CreatedAt string
	UpdatedAt string
}{
	ID:        "fleet_groups.id",
	Name:      "fleet_groups.name",
	Color:     "fleet_groups.color",
	TenantID:  "fleet_groups.tenant_id",
	CreatedAt: "fleet_groups.created_at",
	UpdatedAt: "fleet_groups.updated_at",
}

// Generated where

type whereHelperstring struct{ field string }

func (w whereHelperstring) EQ(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperstring) NEQ(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperstring) LT(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperstring) LTE(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperstring) GT(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperstring) GTE(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperstring) LIKE(x string) qm.QueryMod    { return qm.Where(w.field+" LIKE ?", x) }
func (w whereHelperstring) NLIKE(x string) qm.QueryMod   { return qm.Where(w.field+" NOT LIKE ?", x) }
func (w whereHelperstring) ILIKE(x string) qm.QueryMod   { return qm.Where(w.field+" ILIKE ?", x) }
func (w whereHelperstring) NILIKE(x string) qm.QueryMod  { return qm.Where(w.field+" NOT ILIKE ?", x) }
func (w whereHelperstring) SIMILAR(x string) qm.QueryMod { return qm.Where(w.field+" SIMILAR TO ?", x) }
func (w whereHelperstring) NSIMILAR(x string) qm.QueryMod {
	return qm.Where(w.field+" NOT SIMILAR TO ?", x)
}
func (w whereHelperstring) IN(slice []string) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperstring) NIN(slice []string) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelpertime_Time struct{ field string }

func (w whereHelpertime_Time) EQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertime_Time) NEQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertime_Time) LT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertime_Time) LTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertime_Time) GT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertime_Time) GTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

var FleetGroupWhere = struct {
	ID        whereHelperstring
	Name      whereHelperstring
	Color     whereHelperstring
	TenantID  whereHelperstring
	CreatedAt whereHelpertime_Time
	UpdatedAt whereHelpertime_Time
}{
	ID:        whereHelperstring{field: "\"fleet_groups\".\"id\""},
	Name:      whereHelperstring{field: "\"fleet_groups\".\"name\""},
	Color:     whereHelperstring{field: "\"fleet_groups\".\"color\""},
	TenantID:  whereHelperstring{field: "\"fleet_groups\".\"tenant_id\""},
	CreatedAt: whereHelpertime_Time{field: "\"fleet_groups\".\"created_at\""},
	UpdatedAt: whereHelpertime_Time{field: "\"fleet_groups\".\"updated_at\""},
}

// FleetGroupRels is where relationship names are stored.
var FleetGroupRels = struct {
	Tenant             string
	VehicleFleetGroups string
}{
	Tenant:             "Tenant",
	VehicleFleetGroups: "VehicleFleetGroups",
}

// fleetGroupR is where relationships are stored.
type fleetGroupR struct {
	Tenant             *Tenant                `boil:"Tenant" json:"Tenant" toml:"Tenant" yaml:"Tenant"`
	VehicleFleetGroups VehicleFleetGroupSlice `boil:"VehicleFleetGroups" json:"VehicleFleetGroups" toml:"VehicleFleetGroups" yaml:"VehicleFleetGroups"`
}

// NewStruct creates a new relationship struct
func (*fleetGroupR) NewStruct() *fleetGroupR {
	return &fleetGroupR{}
}

func (o *FleetGroup) GetTenant() *Tenant {
	if o == nil {
		return nil
	}

	return o.R.GetTenant()
}

func (r *fleetGroupR) GetTenant() *Tenant {
	if r == nil {
		return nil
	}

	return r.Tenant
}

func (o *FleetGroup) GetVehicleFleetGroups() VehicleFleetGroupSlice {
	if o == nil {
		return nil
	}

	return o.R.GetVehicleFleetGroups()
}

func (r *fleetGroupR) GetVehicleFleetGroups() VehicleFleetGroupSlice {
	if r == nil {
		return nil
	}

	return r.VehicleFleetGroups
}

// fleetGroupL is where Load methods for each relationship are stored.
type fleetGroupL struct{}

var (
	fleetGroupAllColumns            = []string{"id", "name", "color", "tenant_id", "created_at", "updated_at"}
	fleetGroupColumnsWithoutDefault = []string{"id", "name", "color", "tenant_id"}
	fleetGroupColumnsWithDefault    = []string{"created_at", "updated_at"}
	fleetGroupPrimaryKeyColumns     = []string{"id"}
	fleetGroupGeneratedColumns      = []string{}
)

type (
	// FleetGroupSlice is an alias for a slice of pointers to FleetGroup.
	// This should almost always be used instead of []FleetGroup.
	FleetGroupSlice []*FleetGroup
	// FleetGroupHook is the signature for custom FleetGroup hook methods
	FleetGroupHook func(context.Context, boil.ContextExecutor, *FleetGroup) error

	fleetGroupQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	fleetGroupType                 = reflect.TypeOf(&FleetGroup{})
	fleetGroupMapping              = queries.MakeStructMapping(fleetGroupType)
	fleetGroupPrimaryKeyMapping, _ = queries.BindMapping(fleetGroupType, fleetGroupMapping, fleetGroupPrimaryKeyColumns)
	fleetGroupInsertCacheMut       sync.RWMutex
	fleetGroupInsertCache          = make(map[string]insertCache)
	fleetGroupUpdateCacheMut       sync.RWMutex
	fleetGroupUpdateCache          = make(map[string]updateCache)
	fleetGroupUpsertCacheMut       sync.RWMutex
	fleetGroupUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var fleetGroupAfterSelectMu sync.Mutex
var fleetGroupAfterSelectHooks []FleetGroupHook

var fleetGroupBeforeInsertMu sync.Mutex
var fleetGroupBeforeInsertHooks []FleetGroupHook
var fleetGroupAfterInsertMu sync.Mutex
var fleetGroupAfterInsertHooks []FleetGroupHook

var fleetGroupBeforeUpdateMu sync.Mutex
var fleetGroupBeforeUpdateHooks []FleetGroupHook
var fleetGroupAfterUpdateMu sync.Mutex
var fleetGroupAfterUpdateHooks []FleetGroupHook

var fleetGroupBeforeDeleteMu sync.Mutex
var fleetGroupBeforeDeleteHooks []FleetGroupHook
var fleetGroupAfterDeleteMu sync.Mutex
var fleetGroupAfterDeleteHooks []FleetGroupHook

var fleetGroupBeforeUpsertMu sync.Mutex
var fleetGroupBeforeUpsertHooks []FleetGroupHook
var fleetGroupAfterUpsertMu sync.Mutex
var fleetGroupAfterUpsertHooks []FleetGroupHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *FleetGroup) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range fleetGroupAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *FleetGroup) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range fleetGroupBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *FleetGroup) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range fleetGroupAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *FleetGroup) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range fleetGroupBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *FleetGroup) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range fleetGroupAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *FleetGroup) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range fleetGroupBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *FleetGroup) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range fleetGroupAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *FleetGroup) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range fleetGroupBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *FleetGroup) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range fleetGroupAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddFleetGroupHook registers your hook function for all future operations.
func AddFleetGroupHook(hookPoint boil.HookPoint, fleetGroupHook FleetGroupHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		fleetGroupAfterSelectMu.Lock()
		fleetGroupAfterSelectHooks = append(fleetGroupAfterSelectHooks, fleetGroupHook)
		fleetGroupAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		fleetGroupBeforeInsertMu.Lock()
		fleetGroupBeforeInsertHooks = append(fleetGroupBeforeInsertHooks, fleetGroupHook)
		fleetGroupBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		fleetGroupAfterInsertMu.Lock()
		fleetGroupAfterInsertHooks = append(fleetGroupAfterInsertHooks, fleetGroupHook)
		fleetGroupAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		fleetGroupBeforeUpdateMu.Lock()
		fleetGroupBeforeUpdateHooks = append(fleetGroupBeforeUpdateHooks, fleetGroupHook)
		fleetGroupBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		fleetGroupAfterUpdateMu.Lock()
		fleetGroupAfterUpdateHooks = append(fleetGroupAfterUpdateHooks, fleetGroupHook)
		fleetGroupAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		fleetGroupBeforeDeleteMu.Lock()
		fleetGroupBeforeDeleteHooks = append(fleetGroupBeforeDeleteHooks, fleetGroupHook)
		fleetGroupBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		fleetGroupAfterDeleteMu.Lock()
		fleetGroupAfterDeleteHooks = append(fleetGroupAfterDeleteHooks, fleetGroupHook)
		fleetGroupAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		fleetGroupBeforeUpsertMu.Lock()
		fleetGroupBeforeUpsertHooks = append(fleetGroupBeforeUpsertHooks, fleetGroupHook)
		fleetGroupBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		fleetGroupAfterUpsertMu.Lock()
		fleetGroupAfterUpsertHooks = append(fleetGroupAfterUpsertHooks, fleetGroupHook)
		fleetGroupAfterUpsertMu.Unlock()
	}
}

// One returns a single fleetGroup record from the query.
func (q fleetGroupQuery) One(ctx context.Context, exec boil.ContextExecutor) (*FleetGroup, error) {
	o := &FleetGroup{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for fleet_groups")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all FleetGroup records from the query.
func (q fleetGroupQuery) All(ctx context.Context, exec boil.ContextExecutor) (FleetGroupSlice, error) {
	var o []*FleetGroup

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to FleetGroup slice")
	}

	if len(fleetGroupAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all FleetGroup records in the query.
func (q fleetGroupQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count fleet_groups rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q fleetGroupQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if fleet_groups exists")
	}

	return count > 0, nil
}

// Tenant pointed to by the foreign key.
func (o *FleetGroup) Tenant(mods ...qm.QueryMod) tenantQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.TenantID),
	}

	queryMods = append(queryMods, mods...)

	return Tenants(queryMods...)
}

// VehicleFleetGroups retrieves all the vehicle_fleet_group's VehicleFleetGroups with an executor.
func (o *FleetGroup) VehicleFleetGroups(mods ...qm.QueryMod) vehicleFleetGroupQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"vehicle_fleet_groups\".\"fleet_group_id\"=?", o.ID),
	)

	return VehicleFleetGroups(queryMods...)
}

// LoadTenant allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (fleetGroupL) LoadTenant(ctx context.Context, e boil.ContextExecutor, singular bool, maybeFleetGroup any, mods queries.Applicator) error {
	var slice []*FleetGroup
	var object *FleetGroup

	if singular {
		var ok bool
		object, ok = maybeFleetGroup.(*FleetGroup)
		if !ok {
			object = new(FleetGroup)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeFleetGroup)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeFleetGroup))
			}
		}
	} else {
		s, ok := maybeFleetGroup.(*[]*FleetGroup)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeFleetGroup)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeFleetGroup))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &fleetGroupR{}
		}
		args[object.TenantID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &fleetGroupR{}
			}

			args[obj.TenantID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`tenants`),
		qm.WhereIn(`tenants.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Tenant")
	}

	var resultSlice []*Tenant
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Tenant")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for tenants")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for tenants")
	}

	if len(tenantAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Tenant = foreign
		if foreign.R == nil {
			foreign.R = &tenantR{}
		}
		foreign.R.FleetGroups = append(foreign.R.FleetGroups, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.TenantID == foreign.ID {
				local.R.Tenant = foreign
				if foreign.R == nil {
					foreign.R = &tenantR{}
				}
				foreign.R.FleetGroups = append(foreign.R.FleetGroups, local)
				break
			}
		}
	}

	return nil
}

// LoadVehicleFleetGroups allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (fleetGroupL) LoadVehicleFleetGroups(ctx context.Context, e boil.ContextExecutor, singular bool, maybeFleetGroup any, mods queries.Applicator) error {
	var slice []*FleetGroup
	var object *FleetGroup

	if singular {
		var ok bool
		object, ok = maybeFleetGroup.(*FleetGroup)
		if !ok {
			object = new(FleetGroup)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeFleetGroup)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeFleetGroup))
			}
		}
	} else {
		s, ok := maybeFleetGroup.(*[]*FleetGroup)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeFleetGroup)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeFleetGroup))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &fleetGroupR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &fleetGroupR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`vehicle_fleet_groups`),
		qm.WhereIn(`vehicle_fleet_groups.fleet_group_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load vehicle_fleet_groups")
	}

	var resultSlice []*VehicleFleetGroup
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice vehicle_fleet_groups")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on vehicle_fleet_groups")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for vehicle_fleet_groups")
	}

	if len(vehicleFleetGroupAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.VehicleFleetGroups = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &vehicleFleetGroupR{}
			}
			foreign.R.FleetGroup = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.FleetGroupID {
				local.R.VehicleFleetGroups = append(local.R.VehicleFleetGroups, foreign)
				if foreign.R == nil {
					foreign.R = &vehicleFleetGroupR{}
				}
				foreign.R.FleetGroup = local
				break
			}
		}
	}

	return nil
}

// SetTenant of the fleetGroup to the related item.
// Sets o.R.Tenant to related.
// Adds o to related.R.FleetGroups.
func (o *FleetGroup) SetTenant(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Tenant) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"fleet_groups\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"tenant_id"}),
		strmangle.WhereClause("\"", "\"", 2, fleetGroupPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.TenantID = related.ID
	if o.R == nil {
		o.R = &fleetGroupR{
			Tenant: related,
		}
	} else {
		o.R.Tenant = related
	}

	if related.R == nil {
		related.R = &tenantR{
			FleetGroups: FleetGroupSlice{o},
		}
	} else {
		related.R.FleetGroups = append(related.R.FleetGroups, o)
	}

	return nil
}

// AddVehicleFleetGroups adds the given related objects to the existing relationships
// of the fleet_group, optionally inserting them as new records.
// Appends related to o.R.VehicleFleetGroups.
// Sets related.R.FleetGroup appropriately.
func (o *FleetGroup) AddVehicleFleetGroups(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*VehicleFleetGroup) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.FleetGroupID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"vehicle_fleet_groups\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"fleet_group_id"}),
				strmangle.WhereClause("\"", "\"", 2, vehicleFleetGroupPrimaryKeyColumns),
			)
			values := []any{o.ID, rel.TenantID, rel.TokenID, rel.FleetGroupID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.FleetGroupID = o.ID
		}
	}

	if o.R == nil {
		o.R = &fleetGroupR{
			VehicleFleetGroups: related,
		}
	} else {
		o.R.VehicleFleetGroups = append(o.R.VehicleFleetGroups, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &vehicleFleetGroupR{
				FleetGroup: o,
			}
		} else {
			rel.R.FleetGroup = o
		}
	}
	return nil
}

// FleetGroups retrieves all the records using an executor.
func FleetGroups(mods ...qm.QueryMod) fleetGroupQuery {
	mods = append(mods, qm.From("\"fleet_groups\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"fleet_groups\".*"})
	}

	return fleetGroupQuery{q}
}

// FindFleetGroup retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindFleetGroup(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*FleetGroup, error) {
	fleetGroupObj := &FleetGroup{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"fleet_groups\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, fleetGroupObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from fleet_groups")
	}

	if err = fleetGroupObj.doAfterSelectHooks(ctx, exec); err != nil {
		return fleetGroupObj, err
	}

	return fleetGroupObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *FleetGroup) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no fleet_groups provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(fleetGroupColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	fleetGroupInsertCacheMut.RLock()
	cache, cached := fleetGroupInsertCache[key]
	fleetGroupInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			fleetGroupAllColumns,
			fleetGroupColumnsWithDefault,
			fleetGroupColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(fleetGroupType, fleetGroupMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(fleetGroupType, fleetGroupMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"fleet_groups\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"fleet_groups\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into fleet_groups")
	}

	if !cached {
		fleetGroupInsertCacheMut.Lock()
		fleetGroupInsertCache[key] = cache
		fleetGroupInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the FleetGroup.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *FleetGroup) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	fleetGroupUpdateCacheMut.RLock()
	cache, cached := fleetGroupUpdateCache[key]
	fleetGroupUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			fleetGroupAllColumns,
			fleetGroupPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update fleet_groups, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"fleet_groups\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, fleetGroupPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(fleetGroupType, fleetGroupMapping, append(wl, fleetGroupPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update fleet_groups row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for fleet_groups")
	}

	if !cached {
		fleetGroupUpdateCacheMut.Lock()
		fleetGroupUpdateCache[key] = cache
		fleetGroupUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q fleetGroupQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for fleet_groups")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for fleet_groups")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o FleetGroupSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), fleetGroupPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"fleet_groups\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, fleetGroupPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in fleetGroup slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all fleetGroup")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *FleetGroup) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no fleet_groups provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(fleetGroupColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	fleetGroupUpsertCacheMut.RLock()
	cache, cached := fleetGroupUpsertCache[key]
	fleetGroupUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			fleetGroupAllColumns,
			fleetGroupColumnsWithDefault,
			fleetGroupColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			fleetGroupAllColumns,
			fleetGroupPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert fleet_groups, could not build update column list")
		}

		ret := strmangle.SetComplement(fleetGroupAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(fleetGroupPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert fleet_groups, could not build conflict column list")
			}

			conflict = make([]string, len(fleetGroupPrimaryKeyColumns))
			copy(conflict, fleetGroupPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"fleet_groups\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(fleetGroupType, fleetGroupMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(fleetGroupType, fleetGroupMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert fleet_groups")
	}

	if !cached {
		fleetGroupUpsertCacheMut.Lock()
		fleetGroupUpsertCache[key] = cache
		fleetGroupUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single FleetGroup record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *FleetGroup) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no FleetGroup provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), fleetGroupPrimaryKeyMapping)
	sql := "DELETE FROM \"fleet_groups\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from fleet_groups")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for fleet_groups")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q fleetGroupQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no fleetGroupQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from fleet_groups")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for fleet_groups")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o FleetGroupSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(fleetGroupBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), fleetGroupPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"fleet_groups\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, fleetGroupPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from fleetGroup slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for fleet_groups")
	}

	if len(fleetGroupAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *FleetGroup) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindFleetGroup(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *FleetGroupSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := FleetGroupSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), fleetGroupPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"fleet_groups\".* FROM \"fleet_groups\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, fleetGroupPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in FleetGroupSlice")
	}

	*o = slice

	return nil
}

// FleetGroupExists checks if the FleetGroup row exists.
func FleetGroupExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"fleet_groups\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if fleet_groups exists")
	}

	return exists, nil
}

// Exists checks if the FleetGroup row exists.
func (o *FleetGroup) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return FleetGroupExists(ctx, exec, o.ID)
}
