// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// GeofenceScanCoverage is an object representing the database table.
type GeofenceScanCoverage struct {
	GeofenceID  string    `boil:"geofence_id" json:"geofence_id" toml:"geofence_id" yaml:"geofence_id"`
	TenantID    string    `boil:"tenant_id" json:"tenant_id" toml:"tenant_id" yaml:"tenant_id"`
	TokenID     int64     `boil:"token_id" json:"token_id" toml:"token_id" yaml:"token_id"`
	ScannedFrom time.Time `boil:"scanned_from" json:"scanned_from" toml:"scanned_from" yaml:"scanned_from"`
	ScannedTo   time.Time `boil:"scanned_to" json:"scanned_to" toml:"scanned_to" yaml:"scanned_to"`
	CreatedAt   time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *geofenceScanCoverageR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L geofenceScanCoverageL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var GeofenceScanCoverageColumns = struct {
	GeofenceID  string
	TenantID    string
	TokenID     string
	ScannedFrom string
	ScannedTo   string
	CreatedAt   string
}{
	GeofenceID:  "geofence_id",
	TenantID:    "tenant_id",
	TokenID:     "token_id",
	ScannedFrom: "scanned_from",
	ScannedTo:   "scanned_to",
	CreatedAt:   "created_at",
}

var GeofenceScanCoverageTableColumns = struct {
	GeofenceID  string
	TenantID    string
	TokenID     string
	ScannedFrom string
	ScannedTo   string
	CreatedAt   string
}{
	GeofenceID:  "geofence_scan_coverage.geofence_id",
	TenantID:    "geofence_scan_coverage.tenant_id",
	TokenID:     "geofence_scan_coverage.token_id",
	ScannedFrom: "geofence_scan_coverage.scanned_from",
	ScannedTo:   "geofence_scan_coverage.scanned_to",
	CreatedAt:   "geofence_scan_coverage.created_at",
}

// Generated where

var GeofenceScanCoverageWhere = struct {
	GeofenceID  whereHelperstring
	TenantID    whereHelperstring
	TokenID     whereHelperint64
	ScannedFrom whereHelpertime_Time
	ScannedTo   whereHelpertime_Time
	CreatedAt   whereHelpertime_Time
}{
	GeofenceID:  whereHelperstring{field: "\"geofence_scan_coverage\".\"geofence_id\""},
	TenantID:    whereHelperstring{field: "\"geofence_scan_coverage\".\"tenant_id\""},
	TokenID:     whereHelperint64{field: "\"geofence_scan_coverage\".\"token_id\""},
	ScannedFrom: whereHelpertime_Time{field: "\"geofence_scan_coverage\".\"scanned_from\""},
	ScannedTo:   whereHelpertime_Time{field: "\"geofence_scan_coverage\".\"scanned_to\""},
	CreatedAt:   whereHelpertime_Time{field: "\"geofence_scan_coverage\".\"created_at\""},
}

// GeofenceScanCoverageRels is where relationship names are stored.
var GeofenceScanCoverageRels = struct {
	Geofence string
}{
	Geofence: "Geofence",
}

// geofenceScanCoverageR is where relationships are stored.
type geofenceScanCoverageR struct {
	Geofence *Geofence `boil:"Geofence" json:"Geofence" toml:"Geofence" yaml:"Geofence"`
}

// NewStruct creates a new relationship struct
func (*geofenceScanCoverageR) NewStruct() *geofenceScanCoverageR {
	return &geofenceScanCoverageR{}
}

func (o *GeofenceScanCoverage) GetGeofence() *Geofence {
	if o == nil {
		return nil
	}

	return o.R.GetGeofence()
}

func (r *geofenceScanCoverageR) GetGeofence() *Geofence {
	if r == nil {
		return nil
	}

	return r.Geofence
}

// geofenceScanCoverageL is where Load methods for each relationship are stored.
type geofenceScanCoverageL struct{}

var (
	geofenceScanCoverageAllColumns            = []string{"geofence_id", "tenant_id", "token_id", "scanned_from", "scanned_to", "created_at"}
	geofenceScanCoverageColumnsWithoutDefault = []string{"geofence_id", "tenant_id", "token_id", "scanned_from", "scanned_to"}
	geofenceScanCoverageColumnsWithDefault    = []string{"created_at"}
	geofenceScanCoveragePrimaryKeyColumns     = []string{"geofence_id", "token_id", "scanned_from"}
	geofenceScanCoverageGeneratedColumns      = []string{}
)

type (
	// GeofenceScanCoverageSlice is an alias for a slice of pointers to GeofenceScanCoverage.
	// This should almost always be used instead of []GeofenceScanCoverage.
	GeofenceScanCoverageSlice []*GeofenceScanCoverage
	// GeofenceScanCoverageHook is the signature for custom GeofenceScanCoverage hook methods
	GeofenceScanCoverageHook func(context.Context, boil.ContextExecutor, *GeofenceScanCoverage) error

	geofenceScanCoverageQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	geofenceScanCoverageType                 = reflect.TypeOf(&GeofenceScanCoverage{})
	geofenceScanCoverageMapping              = queries.MakeStructMapping(geofenceScanCoverageType)
	geofenceScanCoveragePrimaryKeyMapping, _ = queries.BindMapping(geofenceScanCoverageType, geofenceScanCoverageMapping, geofenceScanCoveragePrimaryKeyColumns)
	geofenceScanCoverageInsertCacheMut       sync.RWMutex
	geofenceScanCoverageInsertCache          = make(map[string]insertCache)
	geofenceScanCoverageUpdateCacheMut       sync.RWMutex
	geofenceScanCoverageUpdateCache          = make(map[string]updateCache)
	geofenceScanCoverageUpsertCacheMut       sync.RWMutex
	geofenceScanCoverageUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var geofenceScanCoverageAfterSelectMu sync.Mutex
var geofenceScanCoverageAfterSelectHooks []GeofenceScanCoverageHook

var geofenceScanCoverageBeforeInsertMu sync.Mutex
var geofenceScanCoverageBeforeInsertHooks []GeofenceScanCoverageHook
var geofenceScanCoverageAfterInsertMu sync.Mutex
var geofenceScanCoverageAfterInsertHooks []GeofenceScanCoverageHook

var geofenceScanCoverageBeforeUpdateMu sync.Mutex
var geofenceScanCoverageBeforeUpdateHooks []GeofenceScanCoverageHook
var geofenceScanCoverageAfterUpdateMu sync.Mutex
var geofenceScanCoverageAfterUpdateHooks []GeofenceScanCoverageHook

var geofenceScanCoverageBeforeDeleteMu sync.Mutex
var geofenceScanCoverageBeforeDeleteHooks []GeofenceScanCoverageHook
var geofenceScanCoverageAfterDeleteMu sync.Mutex
var geofenceScanCoverageAfterDeleteHooks []GeofenceScanCoverageHook

var geofenceScanCoverageBeforeUpsertMu sync.Mutex
var geofenceScanCoverageBeforeUpsertHooks []GeofenceScanCoverageHook
var geofenceScanCoverageAfterUpsertMu sync.Mutex
var geofenceScanCoverageAfterUpsertHooks []GeofenceScanCoverageHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *GeofenceScanCoverage) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range geofenceScanCoverageAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *GeofenceScanCoverage) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range geofenceScanCoverageBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *GeofenceScanCoverage) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range geofenceScanCoverageAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *GeofenceScanCoverage) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range geofenceScanCoverageBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *GeofenceScanCoverage) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range geofenceScanCoverageAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *GeofenceScanCoverage) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range geofenceScanCoverageBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *GeofenceScanCoverage) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range geofenceScanCoverageAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *GeofenceScanCoverage) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range geofenceScanCoverageBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *GeofenceScanCoverage) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range geofenceScanCoverageAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddGeofenceScanCoverageHook registers your hook function for all future operations.
func AddGeofenceScanCoverageHook(hookPoint boil.HookPoint, geofenceScanCoverageHook GeofenceScanCoverageHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		geofenceScanCoverageAfterSelectMu.Lock()
		geofenceScanCoverageAfterSelectHooks = append(geofenceScanCoverageAfterSelectHooks, geofenceScanCoverageHook)
		geofenceScanCoverageAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		geofenceScanCoverageBeforeInsertMu.Lock()
		geofenceScanCoverageBeforeInsertHooks = append(geofenceScanCoverageBeforeInsertHooks, geofenceScanCoverageHook)
		geofenceScanCoverageBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		geofenceScanCoverageAfterInsertMu.Lock()
		geofenceScanCoverageAfterInsertHooks = append(geofenceScanCoverageAfterInsertHooks, geofenceScanCoverageHook)
		geofenceScanCoverageAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		geofenceScanCoverageBeforeUpdateMu.Lock()
		geofenceScanCoverageBeforeUpdateHooks = append(geofenceScanCoverageBeforeUpdateHooks, geofenceScanCoverageHook)
		geofenceScanCoverageBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		geofenceScanCoverageAfterUpdateMu.Lock()
		geofenceScanCoverageAfterUpdateHooks = append(geofenceScanCoverageAfterUpdateHooks, geofenceScanCoverageHook)
		geofenceScanCoverageAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		geofenceScanCoverageBeforeDeleteMu.Lock()
		geofenceScanCoverageBeforeDeleteHooks = append(geofenceScanCoverageBeforeDeleteHooks, geofenceScanCoverageHook)
		geofenceScanCoverageBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		geofenceScanCoverageAfterDeleteMu.Lock()
		geofenceScanCoverageAfterDeleteHooks = append(geofenceScanCoverageAfterDeleteHooks, geofenceScanCoverageHook)
		geofenceScanCoverageAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		geofenceScanCoverageBeforeUpsertMu.Lock()
		geofenceScanCoverageBeforeUpsertHooks = append(geofenceScanCoverageBeforeUpsertHooks, geofenceScanCoverageHook)
		geofenceScanCoverageBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		geofenceScanCoverageAfterUpsertMu.Lock()
		geofenceScanCoverageAfterUpsertHooks = append(geofenceScanCoverageAfterUpsertHooks, geofenceScanCoverageHook)
		geofenceScanCoverageAfterUpsertMu.Unlock()
	}
}

// One returns a single geofenceScanCoverage record from the query.
func (q geofenceScanCoverageQuery) One(ctx context.Context, exec boil.ContextExecutor) (*GeofenceScanCoverage, error) {
	o := &GeofenceScanCoverage{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for geofence_scan_coverage")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all GeofenceScanCoverage records from the query.
func (q geofenceScanCoverageQuery) All(ctx context.Context, exec boil.ContextExecutor) (GeofenceScanCoverageSlice, error) {
	var o []*GeofenceScanCoverage

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to GeofenceScanCoverage slice")
	}

	if len(geofenceScanCoverageAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all GeofenceScanCoverage records in the query.
func (q geofenceScanCoverageQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count geofence_scan_coverage rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q geofenceScanCoverageQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if geofence_scan_coverage exists")
	}

	return count > 0, nil
}

// Geofence pointed to by the foreign key.
func (o *GeofenceScanCoverage) Geofence(mods ...qm.QueryMod) geofenceQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.GeofenceID),
	}

	queryMods = append(queryMods, mods...)

	return Geofences(queryMods...)
}

// LoadGeofence allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (geofenceScanCoverageL) LoadGeofence(ctx context.Context, e boil.ContextExecutor, singular bool, maybeGeofenceScanCoverage any, mods queries.Applicator) error {
	var slice []*GeofenceScanCoverage
	var object *GeofenceScanCoverage

	if singular {
		var ok bool
		object, ok = maybeGeofenceScanCoverage.(*GeofenceScanCoverage)
		if !ok {
			object = new(GeofenceScanCoverage)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeGeofenceScanCoverage)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeGeofenceScanCoverage))
			}
		}
	} else {
		s, ok := maybeGeofenceScanCoverage.(*[]*GeofenceScanCoverage)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeGeofenceScanCoverage)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeGeofenceScanCoverage))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &geofenceScanCoverageR{}
		}
		args[object.GeofenceID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &geofenceScanCoverageR{}
			}

			args[obj.GeofenceID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`geofences`),
		qm.WhereIn(`geofences.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Geofence")
	}

	var resultSlice []*Geofence
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Geofence")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for geofences")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for geofences")
	}

	if len(geofenceAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Geofence = foreign
		if foreign.R == nil {
			foreign.R = &geofenceR{}
		}
		foreign.R.GeofenceScanCoverages = append(foreign.R.GeofenceScanCoverages, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.GeofenceID == foreign.ID {
				local.R.Geofence = foreign
				if foreign.R == nil {
					foreign.R = &geofenceR{}
				}
				foreign.R.GeofenceScanCoverages = append(foreign.R.GeofenceScanCoverages, local)
				break
			}
		}
	}

	return nil
}

// SetGeofence of the geofenceScanCoverage to the related item.
// Sets o.R.Geofence to related.
// Adds o to related.R.GeofenceScanCoverages.
func (o *GeofenceScanCoverage) SetGeofence(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Geofence) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"geofence_scan_coverage\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"geofence_id"}),
		strmangle.WhereClause("\"", "\"", 2, geofenceScanCoveragePrimaryKeyColumns),
	)
	values := []any{related.ID, o.GeofenceID, o.TokenID, o.ScannedFrom}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.GeofenceID = related.ID
	if o.R == nil {
		o.R = &geofenceScanCoverageR{
			Geofence: related,
		}
	} else {
		o.R.Geofence = related
	}

	if related.R == nil {
		related.R = &geofenceR{
			GeofenceScanCoverages: GeofenceScanCoverageSlice{o},
		}
	} else {
		related.R.GeofenceScanCoverages = append(related.R.GeofenceScanCoverages, o)
	}

	return nil
}

// GeofenceScanCoverages retrieves all the records using an executor.
func GeofenceScanCoverages(mods ...qm.QueryMod) geofenceScanCoverageQuery {
	mods = append(mods, qm.From("\"geofence_scan_coverage\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"geofence_scan_coverage\".*"})
	}

	return geofenceScanCoverageQuery{q}
}

// FindGeofenceScanCoverage retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindGeofenceScanCoverage(ctx context.Context, exec boil.ContextExecutor, geofenceID string, tokenID int64, scannedFrom time.Time, selectCols ...string) (*GeofenceScanCoverage, error) {
	geofenceScanCoverageObj := &GeofenceScanCoverage{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"geofence_scan_coverage\" where \"geofence_id\"=$1 AND \"token_id\"=$2 AND \"scanned_from\"=$3", sel,
	)

	q := queries.Raw(query, geofenceID, tokenID, scannedFrom)

	err := q.Bind(ctx, exec, geofenceScanCoverageObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from geofence_scan_coverage")
	}

	if err = geofenceScanCoverageObj.doAfterSelectHooks(ctx, exec); err != nil {
		return geofenceScanCoverageObj, err
	}

	return geofenceScanCoverageObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *GeofenceScanCoverage) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no geofence_scan_coverage provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(geofenceScanCoverageColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	geofenceScanCoverageInsertCacheMut.RLock()
	cache, cached := geofenceScanCoverageInsertCache[key]
	geofenceScanCoverageInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			geofenceScanCoverageAllColumns,
			geofenceScanCoverageColumnsWithDefault,
			geofenceScanCoverageColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(geofenceScanCoverageType, geofenceScanCoverageMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(geofenceScanCoverageType, geofenceScanCoverageMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"geofence_scan_coverage\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"geofence_scan_coverage\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into geofence_scan_coverage")
	}

	if !cached {
		geofenceScanCoverageInsertCacheMut.Lock()
		geofenceScanCoverageInsertCache[key] = cache
		geofenceScanCoverageInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the GeofenceScanCoverage.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *GeofenceScanCoverage) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	geofenceScanCoverageUpdateCacheMut.RLock()
	cache, cached := geofenceScanCoverageUpdateCache[key]
	geofenceScanCoverageUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			geofenceScanCoverageAllColumns,
			geofenceScanCoveragePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update geofence_scan_coverage, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"geofence_scan_coverage\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, geofenceScanCoveragePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(geofenceScanCoverageType, geofenceScanCoverageMapping, append(wl, geofenceScanCoveragePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update geofence_scan_coverage row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for geofence_scan_coverage")
	}

	if !cached {
		geofenceScanCoverageUpdateCacheMut.Lock()
		geofenceScanCoverageUpdateCache[key] = cache
		geofenceScanCoverageUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q geofenceScanCoverageQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for geofence_scan_coverage")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for geofence_scan_coverage")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o GeofenceScanCoverageSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), geofenceScanCoveragePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"geofence_scan_coverage\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, geofenceScanCoveragePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in geofenceScanCoverage slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all geofenceScanCoverage")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *GeofenceScanCoverage) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no geofence_scan_coverage provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(geofenceScanCoverageColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	geofenceScanCoverageUpsertCacheMut.RLock()
	cache, cached := geofenceScanCoverageUpsertCache[key]
	geofenceScanCoverageUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			geofenceScanCoverageAllColumns,
			geofenceScanCoverageColumnsWithDefault,
			geofenceScanCoverageColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			geofenceScanCoverageAllColumns,
			geofenceScanCoveragePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert geofence_scan_coverage, could not build update column list")
		}

		ret := strmangle.SetComplement(geofenceScanCoverageAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(geofenceScanCoveragePrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert geofence_scan_coverage, could not build conflict column list")
			}

			conflict = make([]string, len(geofenceScanCoveragePrimaryKeyColumns))
			copy(conflict, geofenceScanCoveragePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"geofence_scan_coverage\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(geofenceScanCoverageType, geofenceScanCoverageMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(geofenceScanCoverageType, geofenceScanCoverageMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert geofence_scan_coverage")
	}

	if !cached {
		geofenceScanCoverageUpsertCacheMut.Lock()
		geofenceScanCoverageUpsertCache[key] = cache
		geofenceScanCoverageUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single GeofenceScanCoverage record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *GeofenceScanCoverage) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no GeofenceScanCoverage provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), geofenceScanCoveragePrimaryKeyMapping)
	sql := "DELETE FROM \"geofence_scan_coverage\" WHERE \"geofence_id\"=$1 AND \"token_id\"=$2 AND \"scanned_from\"=$3"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from geofence_scan_coverage")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for geofence_scan_coverage")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q geofenceScanCoverageQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no geofenceScanCoverageQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from geofence_scan_coverage")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for geofence_scan_coverage")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o GeofenceScanCoverageSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(geofenceScanCoverageBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), geofenceScanCoveragePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"geofence_scan_coverage\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, geofenceScanCoveragePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from geofenceScanCoverage slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for geofence_scan_coverage")
	}

	if len(geofenceScanCoverageAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *GeofenceScanCoverage) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindGeofenceScanCoverage(ctx, exec, o.GeofenceID, o.TokenID, o.ScannedFrom)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *GeofenceScanCoverageSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := GeofenceScanCoverageSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), geofenceScanCoveragePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"geofence_scan_coverage\".* FROM \"geofence_scan_coverage\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, geofenceScanCoveragePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in GeofenceScanCoverageSlice")
	}

	*o = slice

	return nil
}

// GeofenceScanCoverageExists checks if the GeofenceScanCoverage row exists.
func GeofenceScanCoverageExists(ctx context.Context, exec boil.ContextExecutor, geofenceID string, tokenID int64, scannedFrom time.Time) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"geofence_scan_coverage\" where \"geofence_id\"=$1 AND \"token_id\"=$2 AND \"scanned_from\"=$3 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, geofenceID, tokenID, scannedFrom)
	}
	row := exec.QueryRowContext(ctx, sql, geofenceID, tokenID, scannedFrom)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if geofence_scan_coverage exists")
	}

	return exists, nil
}

// Exists checks if the GeofenceScanCoverage row exists.
func (o *GeofenceScanCoverage) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return GeofenceScanCoverageExists(ctx, exec, o.GeofenceID, o.TokenID, o.ScannedFrom)
}
