// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// GeofencePass is an object representing the database table.
type GeofencePass struct {
	GeofenceID  string       `boil:"geofence_id" json:"geofence_id" toml:"geofence_id" yaml:"geofence_id"`
	TenantID    string       `boil:"tenant_id" json:"tenant_id" toml:"tenant_id" yaml:"tenant_id"`
	TokenID     int64        `boil:"token_id" json:"token_id" toml:"token_id" yaml:"token_id"`
	EnteredAt   time.Time    `boil:"entered_at" json:"entered_at" toml:"entered_at" yaml:"entered_at"`
	ExitedAt    time.Time    `boil:"exited_at" json:"exited_at" toml:"exited_at" yaml:"exited_at"`
	DwellS      int          `boil:"dwell_s" json:"dwell_s" toml:"dwell_s" yaml:"dwell_s"`
	MaxSpeedKPH null.Float64 `boil:"max_speed_kph" json:"max_speed_kph,omitempty" toml:"max_speed_kph" yaml:"max_speed_kph,omitempty"`
	EntryLat    float64      `boil:"entry_lat" json:"entry_lat" toml:"entry_lat" yaml:"entry_lat"`
	EntryLNG    float64      `boil:"entry_lng" json:"entry_lng" toml:"entry_lng" yaml:"entry_lng"`
	ExitLat     float64      `boil:"exit_lat" json:"exit_lat" toml:"exit_lat" yaml:"exit_lat"`
	ExitLNG     float64      `boil:"exit_lng" json:"exit_lng" toml:"exit_lng" yaml:"exit_lng"`
	MaxSpeedLat null.Float64 `boil:"max_speed_lat" json:"max_speed_lat,omitempty" toml:"max_speed_lat" yaml:"max_speed_lat,omitempty"`
	MaxSpeedLNG null.Float64 `boil:"max_speed_lng" json:"max_speed_lng,omitempty" toml:"max_speed_lng" yaml:"max_speed_lng,omitempty"`
	NumSamples  int          `boil:"num_samples" json:"num_samples" toml:"num_samples" yaml:"num_samples"`
	CreatedAt   time.Time    `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *geofencePassR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L geofencePassL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var GeofencePassColumns = struct {
	GeofenceID  string
	TenantID    string
	TokenID     string
	EnteredAt   string
	ExitedAt    string
	DwellS      string
	MaxSpeedKPH string
	EntryLat    string
	EntryLNG    string
	ExitLat     string
	ExitLNG     string
	MaxSpeedLat string
	MaxSpeedLNG string
	NumSamples  string
	CreatedAt   string
}{
	GeofenceID:  "geofence_id",
	TenantID:    "tenant_id",
	TokenID:     "token_id",
	EnteredAt:   "entered_at",
	ExitedAt:    "exited_at",
	DwellS:      "dwell_s",
	MaxSpeedKPH: "max_speed_kph",
	EntryLat:    "entry_lat",
	EntryLNG:    "entry_lng",
	ExitLat:     "exit_lat",
	ExitLNG:     "exit_lng",
	MaxSpeedLat: "max_speed_lat",
	MaxSpeedLNG: "max_speed_lng",
	NumSamples:  "num_samples",
	CreatedAt:   "created_at",
}

var GeofencePassTableColumns = struct {
	GeofenceID  string
	TenantID    string
	TokenID     string
	EnteredAt   string
	ExitedAt    string
	DwellS      string
	MaxSpeedKPH string
	EntryLat    string
	EntryLNG    string
	ExitLat     string
	ExitLNG     string
	MaxSpeedLat string
	MaxSpeedLNG string
	NumSamples  string
	CreatedAt   string
}{
	GeofenceID:  "geofence_passes.geofence_id",
	TenantID:    "geofence_passes.tenant_id",
	TokenID:     "geofence_passes.token_id",
	EnteredAt:   "geofence_passes.entered_at",
	ExitedAt:    "geofence_passes.exited_at",
	DwellS:      "geofence_passes.dwell_s",
	MaxSpeedKPH: "geofence_passes.max_speed_kph",
	EntryLat:    "geofence_passes.entry_lat",
	EntryLNG:    "geofence_passes.entry_lng",
	ExitLat:     "geofence_passes.exit_lat",
	ExitLNG:     "geofence_passes.exit_lng",
	MaxSpeedLat: "geofence_passes.max_speed_lat",
	MaxSpeedLNG: "geofence_passes.max_speed_lng",
	NumSamples:  "geofence_passes.num_samples",
	CreatedAt:   "geofence_passes.created_at",
}

// Generated where

type whereHelperint64 struct{ field string }

func (w whereHelperint64) EQ(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint64) NEQ(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint64) LT(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint64) LTE(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint64) GT(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint64) GTE(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint64) IN(slice []int64) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint64) NIN(slice []int64) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelperint struct{ field string }

func (w whereHelperint) EQ(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint) NEQ(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint) LT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint) LTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint) GT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint) GTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint) IN(slice []int) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint) NIN(slice []int) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelpernull_Float64 struct{ field string }

func (w whereHelpernull_Float64) EQ(x null.Float64) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Float64) NEQ(x null.Float64) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Float64) LT(x null.Float64) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Float64) LTE(x null.Float64) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Float64) GT(x null.Float64) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Float64) GTE(x null.Float64) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelpernull_Float64) IN(slice []float64) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelpernull_Float64) NIN(slice []float64) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

func (w whereHelpernull_Float64) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Float64) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

type whereHelperfloat64 struct{ field string }

func (w whereHelperfloat64) EQ(x float64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperfloat64) NEQ(x float64) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelperfloat64) LT(x float64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperfloat64) LTE(x float64) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelperfloat64) GT(x float64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperfloat64) GTE(x float64) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelperfloat64) IN(slice []float64) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperfloat64) NIN(slice []float64) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

var GeofencePassWhere = struct {
	GeofenceID  whereHelperstring
	TenantID    whereHelperstring
	TokenID     whereHelperint64
	EnteredAt   whereHelpertime_Time
	ExitedAt    whereHelpertime_Time
	DwellS      whereHelperint
	MaxSpeedKPH whereHelpernull_Float64
	EntryLat    whereHelperfloat64
	EntryLNG    whereHelperfloat64
	ExitLat     whereHelperfloat64
	ExitLNG     whereHelperfloat64
	MaxSpeedLat whereHelpernull_Float64
	MaxSpeedLNG whereHelpernull_Float64
	NumSamples  whereHelperint
	CreatedAt   whereHelpertime_Time
}{
	GeofenceID:  whereHelperstring{field: "\"geofence_passes\".\"geofence_id\""},
	TenantID:    whereHelperstring{field: "\"geofence_passes\".\"tenant_id\""},
	TokenID:     whereHelperint64{field: "\"geofence_passes\".\"token_id\""},
	EnteredAt:   whereHelpertime_Time{field: "\"geofence_passes\".\"entered_at\""},
	ExitedAt:    whereHelpertime_Time{field: "\"geofence_passes\".\"exited_at\""},
	DwellS:      whereHelperint{field: "\"geofence_passes\".\"dwell_s\""},
	MaxSpeedKPH: whereHelpernull_Float64{field: "\"geofence_passes\".\"max_speed_kph\""},
	EntryLat:    whereHelperfloat64{field: "\"geofence_passes\".\"entry_lat\""},
	EntryLNG:    whereHelperfloat64{field: "\"geofence_passes\".\"entry_lng\""},
	ExitLat:     whereHelperfloat64{field: "\"geofence_passes\".\"exit_lat\""},
	ExitLNG:     whereHelperfloat64{field: "\"geofence_passes\".\"exit_lng\""},
	MaxSpeedLat: whereHelpernull_Float64{field: "\"geofence_passes\".\"max_speed_lat\""},
	MaxSpeedLNG: whereHelpernull_Float64{field: "\"geofence_passes\".\"max_speed_lng\""},
	NumSamples:  whereHelperint{field: "\"geofence_passes\".\"num_samples\""},
	CreatedAt:   whereHelpertime_Time{field: "\"geofence_passes\".\"created_at\""},
}

// GeofencePassRels is where relationship names are stored.
var GeofencePassRels = struct {
	Geofence string
}{
	Geofence: "Geofence",
}

// geofencePassR is where relationships are stored.
type geofencePassR struct {
	Geofence *Geofence `boil:"Geofence" json:"Geofence" toml:"Geofence" yaml:"Geofence"`
}

// NewStruct creates a new relationship struct
func (*geofencePassR) NewStruct() *geofencePassR {
	return &geofencePassR{}
}

func (o *GeofencePass) GetGeofence() *Geofence {
	if o == nil {
		return nil
	}

	return o.R.GetGeofence()
}

func (r *geofencePassR) GetGeofence() *Geofence {
	if r == nil {
		return nil
	}

	return r.Geofence
}

// geofencePassL is where Load methods for each relationship are stored.
type geofencePassL struct{}

var (
	geofencePassAllColumns            = []string{"geofence_id", "tenant_id", "token_id", "entered_at", "exited_at", "dwell_s", "max_speed_kph", "entry_lat", "entry_lng", "exit_lat", "exit_lng", "max_speed_lat", "max_speed_lng", "num_samples", "created_at"}
	geofencePassColumnsWithoutDefault = []string{"geofence_id", "tenant_id", "token_id", "entered_at", "exited_at", "dwell_s", "entry_lat", "entry_lng", "exit_lat", "exit_lng", "num_samples"}
	geofencePassColumnsWithDefault    = []string{"max_speed_kph", "max_speed_lat", "max_speed_lng", "created_at"}
	geofencePassPrimaryKeyColumns     = []string{"geofence_id", "token_id", "entered_at"}
	geofencePassGeneratedColumns      = []string{}
)

type (
	// GeofencePassSlice is an alias for a slice of pointers to GeofencePass.
	// This should almost always be used instead of []GeofencePass.
	GeofencePassSlice []*GeofencePass
	// GeofencePassHook is the signature for custom GeofencePass hook methods
	GeofencePassHook func(context.Context, boil.ContextExecutor, *GeofencePass) error

	geofencePassQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	geofencePassType                 = reflect.TypeOf(&GeofencePass{})
	geofencePassMapping              = queries.MakeStructMapping(geofencePassType)
	geofencePassPrimaryKeyMapping, _ = queries.BindMapping(geofencePassType, geofencePassMapping, geofencePassPrimaryKeyColumns)
	geofencePassInsertCacheMut       sync.RWMutex
	geofencePassInsertCache          = make(map[string]insertCache)
	geofencePassUpdateCacheMut       sync.RWMutex
	geofencePassUpdateCache          = make(map[string]updateCache)
	geofencePassUpsertCacheMut       sync.RWMutex
	geofencePassUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var geofencePassAfterSelectMu sync.Mutex
var geofencePassAfterSelectHooks []GeofencePassHook

var geofencePassBeforeInsertMu sync.Mutex
var geofencePassBeforeInsertHooks []GeofencePassHook
var geofencePassAfterInsertMu sync.Mutex
var geofencePassAfterInsertHooks []GeofencePassHook

var geofencePassBeforeUpdateMu sync.Mutex
var geofencePassBeforeUpdateHooks []GeofencePassHook
var geofencePassAfterUpdateMu sync.Mutex
var geofencePassAfterUpdateHooks []GeofencePassHook

var geofencePassBeforeDeleteMu sync.Mutex
var geofencePassBeforeDeleteHooks []GeofencePassHook
var geofencePassAfterDeleteMu sync.Mutex
var geofencePassAfterDeleteHooks []GeofencePassHook

var geofencePassBeforeUpsertMu sync.Mutex
var geofencePassBeforeUpsertHooks []GeofencePassHook
var geofencePassAfterUpsertMu sync.Mutex
var geofencePassAfterUpsertHooks []GeofencePassHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *GeofencePass) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range geofencePassAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *GeofencePass) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range geofencePassBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *GeofencePass) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range geofencePassAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *GeofencePass) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range geofencePassBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *GeofencePass) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range geofencePassAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *GeofencePass) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range geofencePassBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *GeofencePass) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range geofencePassAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *GeofencePass) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range geofencePassBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *GeofencePass) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range geofencePassAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddGeofencePassHook registers your hook function for all future operations.
func AddGeofencePassHook(hookPoint boil.HookPoint, geofencePassHook GeofencePassHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		geofencePassAfterSelectMu.Lock()
		geofencePassAfterSelectHooks = append(geofencePassAfterSelectHooks, geofencePassHook)
		geofencePassAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		geofencePassBeforeInsertMu.Lock()
		geofencePassBeforeInsertHooks = append(geofencePassBeforeInsertHooks, geofencePassHook)
		geofencePassBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		geofencePassAfterInsertMu.Lock()
		geofencePassAfterInsertHooks = append(geofencePassAfterInsertHooks, geofencePassHook)
		geofencePassAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		geofencePassBeforeUpdateMu.Lock()
		geofencePassBeforeUpdateHooks = append(geofencePassBeforeUpdateHooks, geofencePassHook)
		geofencePassBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		geofencePassAfterUpdateMu.Lock()
		geofencePassAfterUpdateHooks = append(geofencePassAfterUpdateHooks, geofencePassHook)
		geofencePassAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		geofencePassBeforeDeleteMu.Lock()
		geofencePassBeforeDeleteHooks = append(geofencePassBeforeDeleteHooks, geofencePassHook)
		geofencePassBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		geofencePassAfterDeleteMu.Lock()
		geofencePassAfterDeleteHooks = append(geofencePassAfterDeleteHooks, geofencePassHook)
		geofencePassAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		geofencePassBeforeUpsertMu.Lock()
		geofencePassBeforeUpsertHooks = append(geofencePassBeforeUpsertHooks, geofencePassHook)
		geofencePassBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		geofencePassAfterUpsertMu.Lock()
		geofencePassAfterUpsertHooks = append(geofencePassAfterUpsertHooks, geofencePassHook)
		geofencePassAfterUpsertMu.Unlock()
	}
}

// One returns a single geofencePass record from the query.
func (q geofencePassQuery) One(ctx context.Context, exec boil.ContextExecutor) (*GeofencePass, error) {
	o := &GeofencePass{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for geofence_passes")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all GeofencePass records from the query.
func (q geofencePassQuery) All(ctx context.Context, exec boil.ContextExecutor) (GeofencePassSlice, error) {
	var o []*GeofencePass

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to GeofencePass slice")
	}

	if len(geofencePassAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all GeofencePass records in the query.
func (q geofencePassQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count geofence_passes rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q geofencePassQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if geofence_passes exists")
	}

	return count > 0, nil
}

// Geofence pointed to by the foreign key.
func (o *GeofencePass) Geofence(mods ...qm.QueryMod) geofenceQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.GeofenceID),
	}

	queryMods = append(queryMods, mods...)

	return Geofences(queryMods...)
}

// LoadGeofence allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (geofencePassL) LoadGeofence(ctx context.Context, e boil.ContextExecutor, singular bool, maybeGeofencePass any, mods queries.Applicator) error {
	var slice []*GeofencePass
	var object *GeofencePass

	if singular {
		var ok bool
		object, ok = maybeGeofencePass.(*GeofencePass)
		if !ok {
			object = new(GeofencePass)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeGeofencePass)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeGeofencePass))
			}
		}
	} else {
		s, ok := maybeGeofencePass.(*[]*GeofencePass)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeGeofencePass)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeGeofencePass))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &geofencePassR{}
		}
		args[object.GeofenceID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &geofencePassR{}
			}

			args[obj.GeofenceID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`geofences`),
		qm.WhereIn(`geofences.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Geofence")
	}

	var resultSlice []*Geofence
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Geofence")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for geofences")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for geofences")
	}

	if len(geofenceAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Geofence = foreign
		if foreign.R == nil {
			foreign.R = &geofenceR{}
		}
		foreign.R.GeofencePasses = append(foreign.R.GeofencePasses, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.GeofenceID == foreign.ID {
				local.R.Geofence = foreign
				if foreign.R == nil {
					foreign.R = &geofenceR{}
				}
				foreign.R.GeofencePasses = append(foreign.R.GeofencePasses, local)
				break
			}
		}
	}

	return nil
}

// SetGeofence of the geofencePass to the related item.
// Sets o.R.Geofence to related.
// Adds o to related.R.GeofencePasses.
func (o *GeofencePass) SetGeofence(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Geofence) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"geofence_passes\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"geofence_id"}),
		strmangle.WhereClause("\"", "\"", 2, geofencePassPrimaryKeyColumns),
	)
	values := []any{related.ID, o.GeofenceID, o.TokenID, o.EnteredAt}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.GeofenceID = related.ID
	if o.R == nil {
		o.R = &geofencePassR{
			Geofence: related,
		}
	} else {
		o.R.Geofence = related
	}

	if related.R == nil {
		related.R = &geofenceR{
			GeofencePasses: GeofencePassSlice{o},
		}
	} else {
		related.R.GeofencePasses = append(related.R.GeofencePasses, o)
	}

	return nil
}

// GeofencePasses retrieves all the records using an executor.
func GeofencePasses(mods ...qm.QueryMod) geofencePassQuery {
	mods = append(mods, qm.From("\"geofence_passes\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"geofence_passes\".*"})
	}

	return geofencePassQuery{q}
}

// FindGeofencePass retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindGeofencePass(ctx context.Context, exec boil.ContextExecutor, geofenceID string, tokenID int64, enteredAt time.Time, selectCols ...string) (*GeofencePass, error) {
	geofencePassObj := &GeofencePass{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"geofence_passes\" where \"geofence_id\"=$1 AND \"token_id\"=$2 AND \"entered_at\"=$3", sel,
	)

	q := queries.Raw(query, geofenceID, tokenID, enteredAt)

	err := q.Bind(ctx, exec, geofencePassObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from geofence_passes")
	}

	if err = geofencePassObj.doAfterSelectHooks(ctx, exec); err != nil {
		return geofencePassObj, err
	}

	return geofencePassObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *GeofencePass) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no geofence_passes provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(geofencePassColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	geofencePassInsertCacheMut.RLock()
	cache, cached := geofencePassInsertCache[key]
	geofencePassInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			geofencePassAllColumns,
			geofencePassColumnsWithDefault,
			geofencePassColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(geofencePassType, geofencePassMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(geofencePassType, geofencePassMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"geofence_passes\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"geofence_passes\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into geofence_passes")
	}

	if !cached {
		geofencePassInsertCacheMut.Lock()
		geofencePassInsertCache[key] = cache
		geofencePassInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the GeofencePass.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *GeofencePass) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	geofencePassUpdateCacheMut.RLock()
	cache, cached := geofencePassUpdateCache[key]
	geofencePassUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			geofencePassAllColumns,
			geofencePassPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update geofence_passes, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"geofence_passes\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, geofencePassPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(geofencePassType, geofencePassMapping, append(wl, geofencePassPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update geofence_passes row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for geofence_passes")
	}

	if !cached {
		geofencePassUpdateCacheMut.Lock()
		geofencePassUpdateCache[key] = cache
		geofencePassUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q geofencePassQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for geofence_passes")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for geofence_passes")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o GeofencePassSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), geofencePassPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"geofence_passes\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, geofencePassPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in geofencePass slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all geofencePass")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *GeofencePass) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no geofence_passes provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(geofencePassColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	geofencePassUpsertCacheMut.RLock()
	cache, cached := geofencePassUpsertCache[key]
	geofencePassUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			geofencePassAllColumns,
			geofencePassColumnsWithDefault,
			geofencePassColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			geofencePassAllColumns,
			geofencePassPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert geofence_passes, could not build update column list")
		}

		ret := strmangle.SetComplement(geofencePassAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(geofencePassPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert geofence_passes, could not build conflict column list")
			}

			conflict = make([]string, len(geofencePassPrimaryKeyColumns))
			copy(conflict, geofencePassPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"geofence_passes\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(geofencePassType, geofencePassMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(geofencePassType, geofencePassMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert geofence_passes")
	}

	if !cached {
		geofencePassUpsertCacheMut.Lock()
		geofencePassUpsertCache[key] = cache
		geofencePassUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single GeofencePass record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *GeofencePass) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no GeofencePass provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), geofencePassPrimaryKeyMapping)
	sql := "DELETE FROM \"geofence_passes\" WHERE \"geofence_id\"=$1 AND \"token_id\"=$2 AND \"entered_at\"=$3"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from geofence_passes")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for geofence_passes")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q geofencePassQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no geofencePassQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from geofence_passes")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for geofence_passes")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o GeofencePassSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(geofencePassBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), geofencePassPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"geofence_passes\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, geofencePassPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from geofencePass slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for geofence_passes")
	}

	if len(geofencePassAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *GeofencePass) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindGeofencePass(ctx, exec, o.GeofenceID, o.TokenID, o.EnteredAt)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *GeofencePassSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := GeofencePassSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), geofencePassPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"geofence_passes\".* FROM \"geofence_passes\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, geofencePassPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in GeofencePassSlice")
	}

	*o = slice

	return nil
}

// GeofencePassExists checks if the GeofencePass row exists.
func GeofencePassExists(ctx context.Context, exec boil.ContextExecutor, geofenceID string, tokenID int64, enteredAt time.Time) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"geofence_passes\" where \"geofence_id\"=$1 AND \"token_id\"=$2 AND \"entered_at\"=$3 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, geofenceID, tokenID, enteredAt)
	}
	row := exec.QueryRowContext(ctx, sql, geofenceID, tokenID, enteredAt)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if geofence_passes exists")
	}

	return exists, nil
}

// Exists checks if the GeofencePass row exists.
func (o *GeofencePass) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return GeofencePassExists(ctx, exec, o.GeofenceID, o.TokenID, o.EnteredAt)
}
