// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/sqlboiler/v4/types"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// TenantUser is an object representing the database table.
type TenantUser struct {
	TenantID        string            `boil:"tenant_id" json:"tenant_id" toml:"tenant_id" yaml:"tenant_id"`
	Wallet          string            `boil:"wallet" json:"wallet" toml:"wallet" yaml:"wallet"`
	Role            string            `boil:"role" json:"role" toml:"role" yaml:"role"`
	CreatedAt       time.Time         `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt       time.Time         `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	LastLoginAt     null.Time         `boil:"last_login_at" json:"last_login_at,omitempty" toml:"last_login_at" yaml:"last_login_at,omitempty"`
	Email           null.String       `boil:"email" json:"email,omitempty" toml:"email" yaml:"email,omitempty"`
	AllowedGroupIds types.StringArray `boil:"allowed_group_ids" json:"allowed_group_ids,omitempty" toml:"allowed_group_ids" yaml:"allowed_group_ids,omitempty"`

	R *tenantUserR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L tenantUserL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var TenantUserColumns = struct {
	TenantID        string
	Wallet          string
	Role            string
	CreatedAt       string
	UpdatedAt       string
	LastLoginAt     string
	Email           string
	AllowedGroupIds string
}{
	TenantID:        "tenant_id",
	Wallet:          "wallet",
	Role:            "role",
	CreatedAt:       "created_at",
	UpdatedAt:       "updated_at",
	LastLoginAt:     "last_login_at",
	Email:           "email",
	AllowedGroupIds: "allowed_group_ids",
}

var TenantUserTableColumns = struct {
	TenantID        string
	Wallet          string
	Role            string
	CreatedAt       string
	UpdatedAt       string
	LastLoginAt     string
	Email           string
	AllowedGroupIds string
}{
	TenantID:        "tenant_users.tenant_id",
	Wallet:          "tenant_users.wallet",
	Role:            "tenant_users.role",
	CreatedAt:       "tenant_users.created_at",
	UpdatedAt:       "tenant_users.updated_at",
	LastLoginAt:     "tenant_users.last_login_at",
	Email:           "tenant_users.email",
	AllowedGroupIds: "tenant_users.allowed_group_ids",
}

// Generated where

var TenantUserWhere = struct {
	TenantID        whereHelperstring
	Wallet          whereHelperstring
	Role            whereHelperstring
	CreatedAt       whereHelpertime_Time
	UpdatedAt       whereHelpertime_Time
	LastLoginAt     whereHelpernull_Time
	Email           whereHelpernull_String
	AllowedGroupIds whereHelpertypes_StringArray
}{
	TenantID:        whereHelperstring{field: "\"tenant_users\".\"tenant_id\""},
	Wallet:          whereHelperstring{field: "\"tenant_users\".\"wallet\""},
	Role:            whereHelperstring{field: "\"tenant_users\".\"role\""},
	CreatedAt:       whereHelpertime_Time{field: "\"tenant_users\".\"created_at\""},
	UpdatedAt:       whereHelpertime_Time{field: "\"tenant_users\".\"updated_at\""},
	LastLoginAt:     whereHelpernull_Time{field: "\"tenant_users\".\"last_login_at\""},
	Email:           whereHelpernull_String{field: "\"tenant_users\".\"email\""},
	AllowedGroupIds: whereHelpertypes_StringArray{field: "\"tenant_users\".\"allowed_group_ids\""},
}

// TenantUserRels is where relationship names are stored.
var TenantUserRels = struct {
	Tenant string
}{
	Tenant: "Tenant",
}

// tenantUserR is where relationships are stored.
type tenantUserR struct {
	Tenant *Tenant `boil:"Tenant" json:"Tenant" toml:"Tenant" yaml:"Tenant"`
}

// NewStruct creates a new relationship struct
func (*tenantUserR) NewStruct() *tenantUserR {
	return &tenantUserR{}
}

func (o *TenantUser) GetTenant() *Tenant {
	if o == nil {
		return nil
	}

	return o.R.GetTenant()
}

func (r *tenantUserR) GetTenant() *Tenant {
	if r == nil {
		return nil
	}

	return r.Tenant
}

// tenantUserL is where Load methods for each relationship are stored.
type tenantUserL struct{}

var (
	tenantUserAllColumns            = []string{"tenant_id", "wallet", "role", "created_at", "updated_at", "last_login_at", "email", "allowed_group_ids"}
	tenantUserColumnsWithoutDefault = []string{"tenant_id", "wallet"}
	tenantUserColumnsWithDefault    = []string{"role", "created_at", "updated_at", "last_login_at", "email", "allowed_group_ids"}
	tenantUserPrimaryKeyColumns     = []string{"tenant_id", "wallet"}
	tenantUserGeneratedColumns      = []string{}
)

type (
	// TenantUserSlice is an alias for a slice of pointers to TenantUser.
	// This should almost always be used instead of []TenantUser.
	TenantUserSlice []*TenantUser
	// TenantUserHook is the signature for custom TenantUser hook methods
	TenantUserHook func(context.Context, boil.ContextExecutor, *TenantUser) error

	tenantUserQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	tenantUserType                 = reflect.TypeOf(&TenantUser{})
	tenantUserMapping              = queries.MakeStructMapping(tenantUserType)
	tenantUserPrimaryKeyMapping, _ = queries.BindMapping(tenantUserType, tenantUserMapping, tenantUserPrimaryKeyColumns)
	tenantUserInsertCacheMut       sync.RWMutex
	tenantUserInsertCache          = make(map[string]insertCache)
	tenantUserUpdateCacheMut       sync.RWMutex
	tenantUserUpdateCache          = make(map[string]updateCache)
	tenantUserUpsertCacheMut       sync.RWMutex
	tenantUserUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var tenantUserAfterSelectMu sync.Mutex
var tenantUserAfterSelectHooks []TenantUserHook

var tenantUserBeforeInsertMu sync.Mutex
var tenantUserBeforeInsertHooks []TenantUserHook
var tenantUserAfterInsertMu sync.Mutex
var tenantUserAfterInsertHooks []TenantUserHook

var tenantUserBeforeUpdateMu sync.Mutex
var tenantUserBeforeUpdateHooks []TenantUserHook
var tenantUserAfterUpdateMu sync.Mutex
var tenantUserAfterUpdateHooks []TenantUserHook

var tenantUserBeforeDeleteMu sync.Mutex
var tenantUserBeforeDeleteHooks []TenantUserHook
var tenantUserAfterDeleteMu sync.Mutex
var tenantUserAfterDeleteHooks []TenantUserHook

var tenantUserBeforeUpsertMu sync.Mutex
var tenantUserBeforeUpsertHooks []TenantUserHook
var tenantUserAfterUpsertMu sync.Mutex
var tenantUserAfterUpsertHooks []TenantUserHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *TenantUser) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tenantUserAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *TenantUser) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tenantUserBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *TenantUser) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tenantUserAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *TenantUser) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tenantUserBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *TenantUser) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tenantUserAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *TenantUser) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tenantUserBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *TenantUser) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tenantUserAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *TenantUser) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tenantUserBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *TenantUser) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tenantUserAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddTenantUserHook registers your hook function for all future operations.
func AddTenantUserHook(hookPoint boil.HookPoint, tenantUserHook TenantUserHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		tenantUserAfterSelectMu.Lock()
		tenantUserAfterSelectHooks = append(tenantUserAfterSelectHooks, tenantUserHook)
		tenantUserAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		tenantUserBeforeInsertMu.Lock()
		tenantUserBeforeInsertHooks = append(tenantUserBeforeInsertHooks, tenantUserHook)
		tenantUserBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		tenantUserAfterInsertMu.Lock()
		tenantUserAfterInsertHooks = append(tenantUserAfterInsertHooks, tenantUserHook)
		tenantUserAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		tenantUserBeforeUpdateMu.Lock()
		tenantUserBeforeUpdateHooks = append(tenantUserBeforeUpdateHooks, tenantUserHook)
		tenantUserBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		tenantUserAfterUpdateMu.Lock()
		tenantUserAfterUpdateHooks = append(tenantUserAfterUpdateHooks, tenantUserHook)
		tenantUserAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		tenantUserBeforeDeleteMu.Lock()
		tenantUserBeforeDeleteHooks = append(tenantUserBeforeDeleteHooks, tenantUserHook)
		tenantUserBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		tenantUserAfterDeleteMu.Lock()
		tenantUserAfterDeleteHooks = append(tenantUserAfterDeleteHooks, tenantUserHook)
		tenantUserAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		tenantUserBeforeUpsertMu.Lock()
		tenantUserBeforeUpsertHooks = append(tenantUserBeforeUpsertHooks, tenantUserHook)
		tenantUserBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		tenantUserAfterUpsertMu.Lock()
		tenantUserAfterUpsertHooks = append(tenantUserAfterUpsertHooks, tenantUserHook)
		tenantUserAfterUpsertMu.Unlock()
	}
}

// One returns a single tenantUser record from the query.
func (q tenantUserQuery) One(ctx context.Context, exec boil.ContextExecutor) (*TenantUser, error) {
	o := &TenantUser{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for tenant_users")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all TenantUser records from the query.
func (q tenantUserQuery) All(ctx context.Context, exec boil.ContextExecutor) (TenantUserSlice, error) {
	var o []*TenantUser

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to TenantUser slice")
	}

	if len(tenantUserAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all TenantUser records in the query.
func (q tenantUserQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count tenant_users rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q tenantUserQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if tenant_users exists")
	}

	return count > 0, nil
}

// Tenant pointed to by the foreign key.
func (o *TenantUser) Tenant(mods ...qm.QueryMod) tenantQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.TenantID),
	}

	queryMods = append(queryMods, mods...)

	return Tenants(queryMods...)
}

// LoadTenant allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (tenantUserL) LoadTenant(ctx context.Context, e boil.ContextExecutor, singular bool, maybeTenantUser any, mods queries.Applicator) error {
	var slice []*TenantUser
	var object *TenantUser

	if singular {
		var ok bool
		object, ok = maybeTenantUser.(*TenantUser)
		if !ok {
			object = new(TenantUser)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeTenantUser)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeTenantUser))
			}
		}
	} else {
		s, ok := maybeTenantUser.(*[]*TenantUser)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeTenantUser)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeTenantUser))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &tenantUserR{}
		}
		args[object.TenantID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &tenantUserR{}
			}

			args[obj.TenantID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`tenants`),
		qm.WhereIn(`tenants.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Tenant")
	}

	var resultSlice []*Tenant
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Tenant")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for tenants")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for tenants")
	}

	if len(tenantAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Tenant = foreign
		if foreign.R == nil {
			foreign.R = &tenantR{}
		}
		foreign.R.TenantUsers = append(foreign.R.TenantUsers, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.TenantID == foreign.ID {
				local.R.Tenant = foreign
				if foreign.R == nil {
					foreign.R = &tenantR{}
				}
				foreign.R.TenantUsers = append(foreign.R.TenantUsers, local)
				break
			}
		}
	}

	return nil
}

// SetTenant of the tenantUser to the related item.
// Sets o.R.Tenant to related.
// Adds o to related.R.TenantUsers.
func (o *TenantUser) SetTenant(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Tenant) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"tenant_users\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"tenant_id"}),
		strmangle.WhereClause("\"", "\"", 2, tenantUserPrimaryKeyColumns),
	)
	values := []any{related.ID, o.TenantID, o.Wallet}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.TenantID = related.ID
	if o.R == nil {
		o.R = &tenantUserR{
			Tenant: related,
		}
	} else {
		o.R.Tenant = related
	}

	if related.R == nil {
		related.R = &tenantR{
			TenantUsers: TenantUserSlice{o},
		}
	} else {
		related.R.TenantUsers = append(related.R.TenantUsers, o)
	}

	return nil
}

// TenantUsers retrieves all the records using an executor.
func TenantUsers(mods ...qm.QueryMod) tenantUserQuery {
	mods = append(mods, qm.From("\"tenant_users\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"tenant_users\".*"})
	}

	return tenantUserQuery{q}
}

// FindTenantUser retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindTenantUser(ctx context.Context, exec boil.ContextExecutor, tenantID string, wallet string, selectCols ...string) (*TenantUser, error) {
	tenantUserObj := &TenantUser{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"tenant_users\" where \"tenant_id\"=$1 AND \"wallet\"=$2", sel,
	)

	q := queries.Raw(query, tenantID, wallet)

	err := q.Bind(ctx, exec, tenantUserObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from tenant_users")
	}

	if err = tenantUserObj.doAfterSelectHooks(ctx, exec); err != nil {
		return tenantUserObj, err
	}

	return tenantUserObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *TenantUser) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no tenant_users provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(tenantUserColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	tenantUserInsertCacheMut.RLock()
	cache, cached := tenantUserInsertCache[key]
	tenantUserInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			tenantUserAllColumns,
			tenantUserColumnsWithDefault,
			tenantUserColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(tenantUserType, tenantUserMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(tenantUserType, tenantUserMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"tenant_users\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"tenant_users\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into tenant_users")
	}

	if !cached {
		tenantUserInsertCacheMut.Lock()
		tenantUserInsertCache[key] = cache
		tenantUserInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the TenantUser.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *TenantUser) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	tenantUserUpdateCacheMut.RLock()
	cache, cached := tenantUserUpdateCache[key]
	tenantUserUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			tenantUserAllColumns,
			tenantUserPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update tenant_users, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"tenant_users\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, tenantUserPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(tenantUserType, tenantUserMapping, append(wl, tenantUserPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update tenant_users row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for tenant_users")
	}

	if !cached {
		tenantUserUpdateCacheMut.Lock()
		tenantUserUpdateCache[key] = cache
		tenantUserUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q tenantUserQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for tenant_users")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for tenant_users")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o TenantUserSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), tenantUserPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"tenant_users\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, tenantUserPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in tenantUser slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all tenantUser")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *TenantUser) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no tenant_users provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(tenantUserColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	tenantUserUpsertCacheMut.RLock()
	cache, cached := tenantUserUpsertCache[key]
	tenantUserUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			tenantUserAllColumns,
			tenantUserColumnsWithDefault,
			tenantUserColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			tenantUserAllColumns,
			tenantUserPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert tenant_users, could not build update column list")
		}

		ret := strmangle.SetComplement(tenantUserAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(tenantUserPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert tenant_users, could not build conflict column list")
			}

			conflict = make([]string, len(tenantUserPrimaryKeyColumns))
			copy(conflict, tenantUserPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"tenant_users\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(tenantUserType, tenantUserMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(tenantUserType, tenantUserMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert tenant_users")
	}

	if !cached {
		tenantUserUpsertCacheMut.Lock()
		tenantUserUpsertCache[key] = cache
		tenantUserUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single TenantUser record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *TenantUser) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no TenantUser provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), tenantUserPrimaryKeyMapping)
	sql := "DELETE FROM \"tenant_users\" WHERE \"tenant_id\"=$1 AND \"wallet\"=$2"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from tenant_users")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for tenant_users")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q tenantUserQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no tenantUserQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from tenant_users")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for tenant_users")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o TenantUserSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(tenantUserBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), tenantUserPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"tenant_users\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, tenantUserPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from tenantUser slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for tenant_users")
	}

	if len(tenantUserAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *TenantUser) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindTenantUser(ctx, exec, o.TenantID, o.Wallet)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *TenantUserSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := TenantUserSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), tenantUserPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"tenant_users\".* FROM \"tenant_users\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, tenantUserPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in TenantUserSlice")
	}

	*o = slice

	return nil
}

// TenantUserExists checks if the TenantUser row exists.
func TenantUserExists(ctx context.Context, exec boil.ContextExecutor, tenantID string, wallet string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"tenant_users\" where \"tenant_id\"=$1 AND \"wallet\"=$2 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, tenantID, wallet)
	}
	row := exec.QueryRowContext(ctx, sql, tenantID, wallet)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if tenant_users exists")
	}

	return exists, nil
}

// Exists checks if the TenantUser row exists.
func (o *TenantUser) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return TenantUserExists(ctx, exec, o.TenantID, o.Wallet)
}
