// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/sqlboiler/v4/types"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// UserPreference is an object representing the database table.
type UserPreference struct {
	Wallet    string     `boil:"wallet" json:"wallet" toml:"wallet" yaml:"wallet"`
	Prefs     types.JSON `boil:"prefs" json:"prefs" toml:"prefs" yaml:"prefs"`
	CreatedAt time.Time  `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt time.Time  `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *userPreferenceR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L userPreferenceL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var UserPreferenceColumns = struct {
	Wallet    string
	Prefs     string
	CreatedAt string
	UpdatedAt string
}{
	Wallet:    "wallet",
	Prefs:     "prefs",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

var UserPreferenceTableColumns = struct {
	Wallet    string
	Prefs     string
	CreatedAt string
	UpdatedAt string
}{
	Wallet:    "user_preferences.wallet",
	Prefs:     "user_preferences.prefs",
	CreatedAt: "user_preferences.created_at",
	UpdatedAt: "user_preferences.updated_at",
}

// Generated where

var UserPreferenceWhere = struct {
	Wallet    whereHelperstring
	Prefs     whereHelpertypes_JSON
	CreatedAt whereHelpertime_Time
	UpdatedAt whereHelpertime_Time
}{
	Wallet:    whereHelperstring{field: "\"user_preferences\".\"wallet\""},
	Prefs:     whereHelpertypes_JSON{field: "\"user_preferences\".\"prefs\""},
	CreatedAt: whereHelpertime_Time{field: "\"user_preferences\".\"created_at\""},
	UpdatedAt: whereHelpertime_Time{field: "\"user_preferences\".\"updated_at\""},
}

// UserPreferenceRels is where relationship names are stored.
var UserPreferenceRels = struct {
}{}

// userPreferenceR is where relationships are stored.
type userPreferenceR struct {
}

// NewStruct creates a new relationship struct
func (*userPreferenceR) NewStruct() *userPreferenceR {
	return &userPreferenceR{}
}

// userPreferenceL is where Load methods for each relationship are stored.
type userPreferenceL struct{}

var (
	userPreferenceAllColumns            = []string{"wallet", "prefs", "created_at", "updated_at"}
	userPreferenceColumnsWithoutDefault = []string{"wallet"}
	userPreferenceColumnsWithDefault    = []string{"prefs", "created_at", "updated_at"}
	userPreferencePrimaryKeyColumns     = []string{"wallet"}
	userPreferenceGeneratedColumns      = []string{}
)

type (
	// UserPreferenceSlice is an alias for a slice of pointers to UserPreference.
	// This should almost always be used instead of []UserPreference.
	UserPreferenceSlice []*UserPreference
	// UserPreferenceHook is the signature for custom UserPreference hook methods
	UserPreferenceHook func(context.Context, boil.ContextExecutor, *UserPreference) error

	userPreferenceQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	userPreferenceType                 = reflect.TypeOf(&UserPreference{})
	userPreferenceMapping              = queries.MakeStructMapping(userPreferenceType)
	userPreferencePrimaryKeyMapping, _ = queries.BindMapping(userPreferenceType, userPreferenceMapping, userPreferencePrimaryKeyColumns)
	userPreferenceInsertCacheMut       sync.RWMutex
	userPreferenceInsertCache          = make(map[string]insertCache)
	userPreferenceUpdateCacheMut       sync.RWMutex
	userPreferenceUpdateCache          = make(map[string]updateCache)
	userPreferenceUpsertCacheMut       sync.RWMutex
	userPreferenceUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var userPreferenceAfterSelectMu sync.Mutex
var userPreferenceAfterSelectHooks []UserPreferenceHook

var userPreferenceBeforeInsertMu sync.Mutex
var userPreferenceBeforeInsertHooks []UserPreferenceHook
var userPreferenceAfterInsertMu sync.Mutex
var userPreferenceAfterInsertHooks []UserPreferenceHook

var userPreferenceBeforeUpdateMu sync.Mutex
var userPreferenceBeforeUpdateHooks []UserPreferenceHook
var userPreferenceAfterUpdateMu sync.Mutex
var userPreferenceAfterUpdateHooks []UserPreferenceHook

var userPreferenceBeforeDeleteMu sync.Mutex
var userPreferenceBeforeDeleteHooks []UserPreferenceHook
var userPreferenceAfterDeleteMu sync.Mutex
var userPreferenceAfterDeleteHooks []UserPreferenceHook

var userPreferenceBeforeUpsertMu sync.Mutex
var userPreferenceBeforeUpsertHooks []UserPreferenceHook
var userPreferenceAfterUpsertMu sync.Mutex
var userPreferenceAfterUpsertHooks []UserPreferenceHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *UserPreference) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userPreferenceAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *UserPreference) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userPreferenceBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *UserPreference) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userPreferenceAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *UserPreference) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userPreferenceBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *UserPreference) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userPreferenceAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *UserPreference) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userPreferenceBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *UserPreference) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userPreferenceAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *UserPreference) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userPreferenceBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *UserPreference) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userPreferenceAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddUserPreferenceHook registers your hook function for all future operations.
func AddUserPreferenceHook(hookPoint boil.HookPoint, userPreferenceHook UserPreferenceHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		userPreferenceAfterSelectMu.Lock()
		userPreferenceAfterSelectHooks = append(userPreferenceAfterSelectHooks, userPreferenceHook)
		userPreferenceAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		userPreferenceBeforeInsertMu.Lock()
		userPreferenceBeforeInsertHooks = append(userPreferenceBeforeInsertHooks, userPreferenceHook)
		userPreferenceBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		userPreferenceAfterInsertMu.Lock()
		userPreferenceAfterInsertHooks = append(userPreferenceAfterInsertHooks, userPreferenceHook)
		userPreferenceAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		userPreferenceBeforeUpdateMu.Lock()
		userPreferenceBeforeUpdateHooks = append(userPreferenceBeforeUpdateHooks, userPreferenceHook)
		userPreferenceBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		userPreferenceAfterUpdateMu.Lock()
		userPreferenceAfterUpdateHooks = append(userPreferenceAfterUpdateHooks, userPreferenceHook)
		userPreferenceAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		userPreferenceBeforeDeleteMu.Lock()
		userPreferenceBeforeDeleteHooks = append(userPreferenceBeforeDeleteHooks, userPreferenceHook)
		userPreferenceBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		userPreferenceAfterDeleteMu.Lock()
		userPreferenceAfterDeleteHooks = append(userPreferenceAfterDeleteHooks, userPreferenceHook)
		userPreferenceAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		userPreferenceBeforeUpsertMu.Lock()
		userPreferenceBeforeUpsertHooks = append(userPreferenceBeforeUpsertHooks, userPreferenceHook)
		userPreferenceBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		userPreferenceAfterUpsertMu.Lock()
		userPreferenceAfterUpsertHooks = append(userPreferenceAfterUpsertHooks, userPreferenceHook)
		userPreferenceAfterUpsertMu.Unlock()
	}
}

// One returns a single userPreference record from the query.
func (q userPreferenceQuery) One(ctx context.Context, exec boil.ContextExecutor) (*UserPreference, error) {
	o := &UserPreference{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for user_preferences")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all UserPreference records from the query.
func (q userPreferenceQuery) All(ctx context.Context, exec boil.ContextExecutor) (UserPreferenceSlice, error) {
	var o []*UserPreference

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to UserPreference slice")
	}

	if len(userPreferenceAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all UserPreference records in the query.
func (q userPreferenceQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count user_preferences rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q userPreferenceQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if user_preferences exists")
	}

	return count > 0, nil
}

// UserPreferences retrieves all the records using an executor.
func UserPreferences(mods ...qm.QueryMod) userPreferenceQuery {
	mods = append(mods, qm.From("\"user_preferences\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"user_preferences\".*"})
	}

	return userPreferenceQuery{q}
}

// FindUserPreference retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindUserPreference(ctx context.Context, exec boil.ContextExecutor, wallet string, selectCols ...string) (*UserPreference, error) {
	userPreferenceObj := &UserPreference{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"user_preferences\" where \"wallet\"=$1", sel,
	)

	q := queries.Raw(query, wallet)

	err := q.Bind(ctx, exec, userPreferenceObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from user_preferences")
	}

	if err = userPreferenceObj.doAfterSelectHooks(ctx, exec); err != nil {
		return userPreferenceObj, err
	}

	return userPreferenceObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *UserPreference) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no user_preferences provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userPreferenceColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	userPreferenceInsertCacheMut.RLock()
	cache, cached := userPreferenceInsertCache[key]
	userPreferenceInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			userPreferenceAllColumns,
			userPreferenceColumnsWithDefault,
			userPreferenceColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(userPreferenceType, userPreferenceMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(userPreferenceType, userPreferenceMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"user_preferences\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"user_preferences\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into user_preferences")
	}

	if !cached {
		userPreferenceInsertCacheMut.Lock()
		userPreferenceInsertCache[key] = cache
		userPreferenceInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the UserPreference.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *UserPreference) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	userPreferenceUpdateCacheMut.RLock()
	cache, cached := userPreferenceUpdateCache[key]
	userPreferenceUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			userPreferenceAllColumns,
			userPreferencePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update user_preferences, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"user_preferences\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, userPreferencePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(userPreferenceType, userPreferenceMapping, append(wl, userPreferencePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update user_preferences row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for user_preferences")
	}

	if !cached {
		userPreferenceUpdateCacheMut.Lock()
		userPreferenceUpdateCache[key] = cache
		userPreferenceUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q userPreferenceQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for user_preferences")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for user_preferences")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o UserPreferenceSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userPreferencePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"user_preferences\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, userPreferencePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in userPreference slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all userPreference")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *UserPreference) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no user_preferences provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userPreferenceColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	userPreferenceUpsertCacheMut.RLock()
	cache, cached := userPreferenceUpsertCache[key]
	userPreferenceUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			userPreferenceAllColumns,
			userPreferenceColumnsWithDefault,
			userPreferenceColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			userPreferenceAllColumns,
			userPreferencePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert user_preferences, could not build update column list")
		}

		ret := strmangle.SetComplement(userPreferenceAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(userPreferencePrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert user_preferences, could not build conflict column list")
			}

			conflict = make([]string, len(userPreferencePrimaryKeyColumns))
			copy(conflict, userPreferencePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"user_preferences\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(userPreferenceType, userPreferenceMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(userPreferenceType, userPreferenceMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert user_preferences")
	}

	if !cached {
		userPreferenceUpsertCacheMut.Lock()
		userPreferenceUpsertCache[key] = cache
		userPreferenceUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single UserPreference record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *UserPreference) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no UserPreference provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), userPreferencePrimaryKeyMapping)
	sql := "DELETE FROM \"user_preferences\" WHERE \"wallet\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from user_preferences")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for user_preferences")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q userPreferenceQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no userPreferenceQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from user_preferences")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for user_preferences")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o UserPreferenceSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(userPreferenceBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userPreferencePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"user_preferences\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, userPreferencePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from userPreference slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for user_preferences")
	}

	if len(userPreferenceAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *UserPreference) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindUserPreference(ctx, exec, o.Wallet)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *UserPreferenceSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := UserPreferenceSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userPreferencePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"user_preferences\".* FROM \"user_preferences\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, userPreferencePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in UserPreferenceSlice")
	}

	*o = slice

	return nil
}

// UserPreferenceExists checks if the UserPreference row exists.
func UserPreferenceExists(ctx context.Context, exec boil.ContextExecutor, wallet string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"user_preferences\" where \"wallet\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, wallet)
	}
	row := exec.QueryRowContext(ctx, sql, wallet)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if user_preferences exists")
	}

	return exists, nil
}

// Exists checks if the UserPreference row exists.
func (o *UserPreference) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return UserPreferenceExists(ctx, exec, o.Wallet)
}
