// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// VehicleFleetGroup is an object representing the database table.
type VehicleFleetGroup struct {
	TenantID     string    `boil:"tenant_id" json:"tenant_id" toml:"tenant_id" yaml:"tenant_id"`
	TokenID      int64     `boil:"token_id" json:"token_id" toml:"token_id" yaml:"token_id"`
	FleetGroupID string    `boil:"fleet_group_id" json:"fleet_group_id" toml:"fleet_group_id" yaml:"fleet_group_id"`
	CreatedAt    time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *vehicleFleetGroupR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L vehicleFleetGroupL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var VehicleFleetGroupColumns = struct {
	TenantID     string
	TokenID      string
	FleetGroupID string
	CreatedAt    string
}{
	TenantID:     "tenant_id",
	TokenID:      "token_id",
	FleetGroupID: "fleet_group_id",
	CreatedAt:    "created_at",
}

var VehicleFleetGroupTableColumns = struct {
	TenantID     string
	TokenID      string
	FleetGroupID string
	CreatedAt    string
}{
	TenantID:     "vehicle_fleet_groups.tenant_id",
	TokenID:      "vehicle_fleet_groups.token_id",
	FleetGroupID: "vehicle_fleet_groups.fleet_group_id",
	CreatedAt:    "vehicle_fleet_groups.created_at",
}

// Generated where

var VehicleFleetGroupWhere = struct {
	TenantID     whereHelperstring
	TokenID      whereHelperint64
	FleetGroupID whereHelperstring
	CreatedAt    whereHelpertime_Time
}{
	TenantID:     whereHelperstring{field: "\"vehicle_fleet_groups\".\"tenant_id\""},
	TokenID:      whereHelperint64{field: "\"vehicle_fleet_groups\".\"token_id\""},
	FleetGroupID: whereHelperstring{field: "\"vehicle_fleet_groups\".\"fleet_group_id\""},
	CreatedAt:    whereHelpertime_Time{field: "\"vehicle_fleet_groups\".\"created_at\""},
}

// VehicleFleetGroupRels is where relationship names are stored.
var VehicleFleetGroupRels = struct {
	FleetGroup string
}{
	FleetGroup: "FleetGroup",
}

// vehicleFleetGroupR is where relationships are stored.
type vehicleFleetGroupR struct {
	FleetGroup *FleetGroup `boil:"FleetGroup" json:"FleetGroup" toml:"FleetGroup" yaml:"FleetGroup"`
}

// NewStruct creates a new relationship struct
func (*vehicleFleetGroupR) NewStruct() *vehicleFleetGroupR {
	return &vehicleFleetGroupR{}
}

func (o *VehicleFleetGroup) GetFleetGroup() *FleetGroup {
	if o == nil {
		return nil
	}

	return o.R.GetFleetGroup()
}

func (r *vehicleFleetGroupR) GetFleetGroup() *FleetGroup {
	if r == nil {
		return nil
	}

	return r.FleetGroup
}

// vehicleFleetGroupL is where Load methods for each relationship are stored.
type vehicleFleetGroupL struct{}

var (
	vehicleFleetGroupAllColumns            = []string{"tenant_id", "token_id", "fleet_group_id", "created_at"}
	vehicleFleetGroupColumnsWithoutDefault = []string{"tenant_id", "token_id", "fleet_group_id"}
	vehicleFleetGroupColumnsWithDefault    = []string{"created_at"}
	vehicleFleetGroupPrimaryKeyColumns     = []string{"tenant_id", "token_id", "fleet_group_id"}
	vehicleFleetGroupGeneratedColumns      = []string{}
)

type (
	// VehicleFleetGroupSlice is an alias for a slice of pointers to VehicleFleetGroup.
	// This should almost always be used instead of []VehicleFleetGroup.
	VehicleFleetGroupSlice []*VehicleFleetGroup
	// VehicleFleetGroupHook is the signature for custom VehicleFleetGroup hook methods
	VehicleFleetGroupHook func(context.Context, boil.ContextExecutor, *VehicleFleetGroup) error

	vehicleFleetGroupQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	vehicleFleetGroupType                 = reflect.TypeOf(&VehicleFleetGroup{})
	vehicleFleetGroupMapping              = queries.MakeStructMapping(vehicleFleetGroupType)
	vehicleFleetGroupPrimaryKeyMapping, _ = queries.BindMapping(vehicleFleetGroupType, vehicleFleetGroupMapping, vehicleFleetGroupPrimaryKeyColumns)
	vehicleFleetGroupInsertCacheMut       sync.RWMutex
	vehicleFleetGroupInsertCache          = make(map[string]insertCache)
	vehicleFleetGroupUpdateCacheMut       sync.RWMutex
	vehicleFleetGroupUpdateCache          = make(map[string]updateCache)
	vehicleFleetGroupUpsertCacheMut       sync.RWMutex
	vehicleFleetGroupUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var vehicleFleetGroupAfterSelectMu sync.Mutex
var vehicleFleetGroupAfterSelectHooks []VehicleFleetGroupHook

var vehicleFleetGroupBeforeInsertMu sync.Mutex
var vehicleFleetGroupBeforeInsertHooks []VehicleFleetGroupHook
var vehicleFleetGroupAfterInsertMu sync.Mutex
var vehicleFleetGroupAfterInsertHooks []VehicleFleetGroupHook

var vehicleFleetGroupBeforeUpdateMu sync.Mutex
var vehicleFleetGroupBeforeUpdateHooks []VehicleFleetGroupHook
var vehicleFleetGroupAfterUpdateMu sync.Mutex
var vehicleFleetGroupAfterUpdateHooks []VehicleFleetGroupHook

var vehicleFleetGroupBeforeDeleteMu sync.Mutex
var vehicleFleetGroupBeforeDeleteHooks []VehicleFleetGroupHook
var vehicleFleetGroupAfterDeleteMu sync.Mutex
var vehicleFleetGroupAfterDeleteHooks []VehicleFleetGroupHook

var vehicleFleetGroupBeforeUpsertMu sync.Mutex
var vehicleFleetGroupBeforeUpsertHooks []VehicleFleetGroupHook
var vehicleFleetGroupAfterUpsertMu sync.Mutex
var vehicleFleetGroupAfterUpsertHooks []VehicleFleetGroupHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *VehicleFleetGroup) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vehicleFleetGroupAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *VehicleFleetGroup) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vehicleFleetGroupBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *VehicleFleetGroup) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vehicleFleetGroupAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *VehicleFleetGroup) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vehicleFleetGroupBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *VehicleFleetGroup) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vehicleFleetGroupAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *VehicleFleetGroup) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vehicleFleetGroupBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *VehicleFleetGroup) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vehicleFleetGroupAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *VehicleFleetGroup) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vehicleFleetGroupBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *VehicleFleetGroup) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vehicleFleetGroupAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddVehicleFleetGroupHook registers your hook function for all future operations.
func AddVehicleFleetGroupHook(hookPoint boil.HookPoint, vehicleFleetGroupHook VehicleFleetGroupHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		vehicleFleetGroupAfterSelectMu.Lock()
		vehicleFleetGroupAfterSelectHooks = append(vehicleFleetGroupAfterSelectHooks, vehicleFleetGroupHook)
		vehicleFleetGroupAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		vehicleFleetGroupBeforeInsertMu.Lock()
		vehicleFleetGroupBeforeInsertHooks = append(vehicleFleetGroupBeforeInsertHooks, vehicleFleetGroupHook)
		vehicleFleetGroupBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		vehicleFleetGroupAfterInsertMu.Lock()
		vehicleFleetGroupAfterInsertHooks = append(vehicleFleetGroupAfterInsertHooks, vehicleFleetGroupHook)
		vehicleFleetGroupAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		vehicleFleetGroupBeforeUpdateMu.Lock()
		vehicleFleetGroupBeforeUpdateHooks = append(vehicleFleetGroupBeforeUpdateHooks, vehicleFleetGroupHook)
		vehicleFleetGroupBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		vehicleFleetGroupAfterUpdateMu.Lock()
		vehicleFleetGroupAfterUpdateHooks = append(vehicleFleetGroupAfterUpdateHooks, vehicleFleetGroupHook)
		vehicleFleetGroupAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		vehicleFleetGroupBeforeDeleteMu.Lock()
		vehicleFleetGroupBeforeDeleteHooks = append(vehicleFleetGroupBeforeDeleteHooks, vehicleFleetGroupHook)
		vehicleFleetGroupBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		vehicleFleetGroupAfterDeleteMu.Lock()
		vehicleFleetGroupAfterDeleteHooks = append(vehicleFleetGroupAfterDeleteHooks, vehicleFleetGroupHook)
		vehicleFleetGroupAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		vehicleFleetGroupBeforeUpsertMu.Lock()
		vehicleFleetGroupBeforeUpsertHooks = append(vehicleFleetGroupBeforeUpsertHooks, vehicleFleetGroupHook)
		vehicleFleetGroupBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		vehicleFleetGroupAfterUpsertMu.Lock()
		vehicleFleetGroupAfterUpsertHooks = append(vehicleFleetGroupAfterUpsertHooks, vehicleFleetGroupHook)
		vehicleFleetGroupAfterUpsertMu.Unlock()
	}
}

// One returns a single vehicleFleetGroup record from the query.
func (q vehicleFleetGroupQuery) One(ctx context.Context, exec boil.ContextExecutor) (*VehicleFleetGroup, error) {
	o := &VehicleFleetGroup{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for vehicle_fleet_groups")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all VehicleFleetGroup records from the query.
func (q vehicleFleetGroupQuery) All(ctx context.Context, exec boil.ContextExecutor) (VehicleFleetGroupSlice, error) {
	var o []*VehicleFleetGroup

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to VehicleFleetGroup slice")
	}

	if len(vehicleFleetGroupAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all VehicleFleetGroup records in the query.
func (q vehicleFleetGroupQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count vehicle_fleet_groups rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q vehicleFleetGroupQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if vehicle_fleet_groups exists")
	}

	return count > 0, nil
}

// FleetGroup pointed to by the foreign key.
func (o *VehicleFleetGroup) FleetGroup(mods ...qm.QueryMod) fleetGroupQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.FleetGroupID),
	}

	queryMods = append(queryMods, mods...)

	return FleetGroups(queryMods...)
}

// LoadFleetGroup allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (vehicleFleetGroupL) LoadFleetGroup(ctx context.Context, e boil.ContextExecutor, singular bool, maybeVehicleFleetGroup any, mods queries.Applicator) error {
	var slice []*VehicleFleetGroup
	var object *VehicleFleetGroup

	if singular {
		var ok bool
		object, ok = maybeVehicleFleetGroup.(*VehicleFleetGroup)
		if !ok {
			object = new(VehicleFleetGroup)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeVehicleFleetGroup)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeVehicleFleetGroup))
			}
		}
	} else {
		s, ok := maybeVehicleFleetGroup.(*[]*VehicleFleetGroup)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeVehicleFleetGroup)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeVehicleFleetGroup))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &vehicleFleetGroupR{}
		}
		args[object.FleetGroupID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &vehicleFleetGroupR{}
			}

			args[obj.FleetGroupID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`fleet_groups`),
		qm.WhereIn(`fleet_groups.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load FleetGroup")
	}

	var resultSlice []*FleetGroup
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice FleetGroup")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for fleet_groups")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for fleet_groups")
	}

	if len(fleetGroupAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.FleetGroup = foreign
		if foreign.R == nil {
			foreign.R = &fleetGroupR{}
		}
		foreign.R.VehicleFleetGroups = append(foreign.R.VehicleFleetGroups, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.FleetGroupID == foreign.ID {
				local.R.FleetGroup = foreign
				if foreign.R == nil {
					foreign.R = &fleetGroupR{}
				}
				foreign.R.VehicleFleetGroups = append(foreign.R.VehicleFleetGroups, local)
				break
			}
		}
	}

	return nil
}

// SetFleetGroup of the vehicleFleetGroup to the related item.
// Sets o.R.FleetGroup to related.
// Adds o to related.R.VehicleFleetGroups.
func (o *VehicleFleetGroup) SetFleetGroup(ctx context.Context, exec boil.ContextExecutor, insert bool, related *FleetGroup) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"vehicle_fleet_groups\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"fleet_group_id"}),
		strmangle.WhereClause("\"", "\"", 2, vehicleFleetGroupPrimaryKeyColumns),
	)
	values := []any{related.ID, o.TenantID, o.TokenID, o.FleetGroupID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.FleetGroupID = related.ID
	if o.R == nil {
		o.R = &vehicleFleetGroupR{
			FleetGroup: related,
		}
	} else {
		o.R.FleetGroup = related
	}

	if related.R == nil {
		related.R = &fleetGroupR{
			VehicleFleetGroups: VehicleFleetGroupSlice{o},
		}
	} else {
		related.R.VehicleFleetGroups = append(related.R.VehicleFleetGroups, o)
	}

	return nil
}

// VehicleFleetGroups retrieves all the records using an executor.
func VehicleFleetGroups(mods ...qm.QueryMod) vehicleFleetGroupQuery {
	mods = append(mods, qm.From("\"vehicle_fleet_groups\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"vehicle_fleet_groups\".*"})
	}

	return vehicleFleetGroupQuery{q}
}

// FindVehicleFleetGroup retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindVehicleFleetGroup(ctx context.Context, exec boil.ContextExecutor, tenantID string, tokenID int64, fleetGroupID string, selectCols ...string) (*VehicleFleetGroup, error) {
	vehicleFleetGroupObj := &VehicleFleetGroup{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"vehicle_fleet_groups\" where \"tenant_id\"=$1 AND \"token_id\"=$2 AND \"fleet_group_id\"=$3", sel,
	)

	q := queries.Raw(query, tenantID, tokenID, fleetGroupID)

	err := q.Bind(ctx, exec, vehicleFleetGroupObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from vehicle_fleet_groups")
	}

	if err = vehicleFleetGroupObj.doAfterSelectHooks(ctx, exec); err != nil {
		return vehicleFleetGroupObj, err
	}

	return vehicleFleetGroupObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *VehicleFleetGroup) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no vehicle_fleet_groups provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(vehicleFleetGroupColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	vehicleFleetGroupInsertCacheMut.RLock()
	cache, cached := vehicleFleetGroupInsertCache[key]
	vehicleFleetGroupInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			vehicleFleetGroupAllColumns,
			vehicleFleetGroupColumnsWithDefault,
			vehicleFleetGroupColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(vehicleFleetGroupType, vehicleFleetGroupMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(vehicleFleetGroupType, vehicleFleetGroupMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"vehicle_fleet_groups\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"vehicle_fleet_groups\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into vehicle_fleet_groups")
	}

	if !cached {
		vehicleFleetGroupInsertCacheMut.Lock()
		vehicleFleetGroupInsertCache[key] = cache
		vehicleFleetGroupInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the VehicleFleetGroup.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *VehicleFleetGroup) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	vehicleFleetGroupUpdateCacheMut.RLock()
	cache, cached := vehicleFleetGroupUpdateCache[key]
	vehicleFleetGroupUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			vehicleFleetGroupAllColumns,
			vehicleFleetGroupPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update vehicle_fleet_groups, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"vehicle_fleet_groups\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, vehicleFleetGroupPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(vehicleFleetGroupType, vehicleFleetGroupMapping, append(wl, vehicleFleetGroupPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update vehicle_fleet_groups row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for vehicle_fleet_groups")
	}

	if !cached {
		vehicleFleetGroupUpdateCacheMut.Lock()
		vehicleFleetGroupUpdateCache[key] = cache
		vehicleFleetGroupUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q vehicleFleetGroupQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for vehicle_fleet_groups")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for vehicle_fleet_groups")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o VehicleFleetGroupSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), vehicleFleetGroupPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"vehicle_fleet_groups\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, vehicleFleetGroupPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in vehicleFleetGroup slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all vehicleFleetGroup")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *VehicleFleetGroup) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no vehicle_fleet_groups provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(vehicleFleetGroupColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	vehicleFleetGroupUpsertCacheMut.RLock()
	cache, cached := vehicleFleetGroupUpsertCache[key]
	vehicleFleetGroupUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			vehicleFleetGroupAllColumns,
			vehicleFleetGroupColumnsWithDefault,
			vehicleFleetGroupColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			vehicleFleetGroupAllColumns,
			vehicleFleetGroupPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert vehicle_fleet_groups, could not build update column list")
		}

		ret := strmangle.SetComplement(vehicleFleetGroupAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(vehicleFleetGroupPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert vehicle_fleet_groups, could not build conflict column list")
			}

			conflict = make([]string, len(vehicleFleetGroupPrimaryKeyColumns))
			copy(conflict, vehicleFleetGroupPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"vehicle_fleet_groups\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(vehicleFleetGroupType, vehicleFleetGroupMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(vehicleFleetGroupType, vehicleFleetGroupMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert vehicle_fleet_groups")
	}

	if !cached {
		vehicleFleetGroupUpsertCacheMut.Lock()
		vehicleFleetGroupUpsertCache[key] = cache
		vehicleFleetGroupUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single VehicleFleetGroup record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *VehicleFleetGroup) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no VehicleFleetGroup provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), vehicleFleetGroupPrimaryKeyMapping)
	sql := "DELETE FROM \"vehicle_fleet_groups\" WHERE \"tenant_id\"=$1 AND \"token_id\"=$2 AND \"fleet_group_id\"=$3"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from vehicle_fleet_groups")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for vehicle_fleet_groups")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q vehicleFleetGroupQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no vehicleFleetGroupQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from vehicle_fleet_groups")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for vehicle_fleet_groups")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o VehicleFleetGroupSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(vehicleFleetGroupBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), vehicleFleetGroupPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"vehicle_fleet_groups\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, vehicleFleetGroupPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from vehicleFleetGroup slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for vehicle_fleet_groups")
	}

	if len(vehicleFleetGroupAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *VehicleFleetGroup) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindVehicleFleetGroup(ctx, exec, o.TenantID, o.TokenID, o.FleetGroupID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *VehicleFleetGroupSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := VehicleFleetGroupSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), vehicleFleetGroupPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"vehicle_fleet_groups\".* FROM \"vehicle_fleet_groups\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, vehicleFleetGroupPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in VehicleFleetGroupSlice")
	}

	*o = slice

	return nil
}

// VehicleFleetGroupExists checks if the VehicleFleetGroup row exists.
func VehicleFleetGroupExists(ctx context.Context, exec boil.ContextExecutor, tenantID string, tokenID int64, fleetGroupID string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"vehicle_fleet_groups\" where \"tenant_id\"=$1 AND \"token_id\"=$2 AND \"fleet_group_id\"=$3 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, tenantID, tokenID, fleetGroupID)
	}
	row := exec.QueryRowContext(ctx, sql, tenantID, tokenID, fleetGroupID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if vehicle_fleet_groups exists")
	}

	return exists, nil
}

// Exists checks if the VehicleFleetGroup row exists.
func (o *VehicleFleetGroup) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return VehicleFleetGroupExists(ctx, exec, o.TenantID, o.TokenID, o.FleetGroupID)
}
