// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// VehicleGeofence is an object representing the database table.
type VehicleGeofence struct {
	TenantID   string    `boil:"tenant_id" json:"tenant_id" toml:"tenant_id" yaml:"tenant_id"`
	TokenID    int64     `boil:"token_id" json:"token_id" toml:"token_id" yaml:"token_id"`
	GeofenceID string    `boil:"geofence_id" json:"geofence_id" toml:"geofence_id" yaml:"geofence_id"`
	CreatedAt  time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *vehicleGeofenceR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L vehicleGeofenceL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var VehicleGeofenceColumns = struct {
	TenantID   string
	TokenID    string
	GeofenceID string
	CreatedAt  string
}{
	TenantID:   "tenant_id",
	TokenID:    "token_id",
	GeofenceID: "geofence_id",
	CreatedAt:  "created_at",
}

var VehicleGeofenceTableColumns = struct {
	TenantID   string
	TokenID    string
	GeofenceID string
	CreatedAt  string
}{
	TenantID:   "vehicle_geofences.tenant_id",
	TokenID:    "vehicle_geofences.token_id",
	GeofenceID: "vehicle_geofences.geofence_id",
	CreatedAt:  "vehicle_geofences.created_at",
}

// Generated where

var VehicleGeofenceWhere = struct {
	TenantID   whereHelperstring
	TokenID    whereHelperint64
	GeofenceID whereHelperstring
	CreatedAt  whereHelpertime_Time
}{
	TenantID:   whereHelperstring{field: "\"vehicle_geofences\".\"tenant_id\""},
	TokenID:    whereHelperint64{field: "\"vehicle_geofences\".\"token_id\""},
	GeofenceID: whereHelperstring{field: "\"vehicle_geofences\".\"geofence_id\""},
	CreatedAt:  whereHelpertime_Time{field: "\"vehicle_geofences\".\"created_at\""},
}

// VehicleGeofenceRels is where relationship names are stored.
var VehicleGeofenceRels = struct {
	Geofence string
}{
	Geofence: "Geofence",
}

// vehicleGeofenceR is where relationships are stored.
type vehicleGeofenceR struct {
	Geofence *Geofence `boil:"Geofence" json:"Geofence" toml:"Geofence" yaml:"Geofence"`
}

// NewStruct creates a new relationship struct
func (*vehicleGeofenceR) NewStruct() *vehicleGeofenceR {
	return &vehicleGeofenceR{}
}

func (o *VehicleGeofence) GetGeofence() *Geofence {
	if o == nil {
		return nil
	}

	return o.R.GetGeofence()
}

func (r *vehicleGeofenceR) GetGeofence() *Geofence {
	if r == nil {
		return nil
	}

	return r.Geofence
}

// vehicleGeofenceL is where Load methods for each relationship are stored.
type vehicleGeofenceL struct{}

var (
	vehicleGeofenceAllColumns            = []string{"tenant_id", "token_id", "geofence_id", "created_at"}
	vehicleGeofenceColumnsWithoutDefault = []string{"tenant_id", "token_id", "geofence_id"}
	vehicleGeofenceColumnsWithDefault    = []string{"created_at"}
	vehicleGeofencePrimaryKeyColumns     = []string{"tenant_id", "token_id", "geofence_id"}
	vehicleGeofenceGeneratedColumns      = []string{}
)

type (
	// VehicleGeofenceSlice is an alias for a slice of pointers to VehicleGeofence.
	// This should almost always be used instead of []VehicleGeofence.
	VehicleGeofenceSlice []*VehicleGeofence
	// VehicleGeofenceHook is the signature for custom VehicleGeofence hook methods
	VehicleGeofenceHook func(context.Context, boil.ContextExecutor, *VehicleGeofence) error

	vehicleGeofenceQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	vehicleGeofenceType                 = reflect.TypeOf(&VehicleGeofence{})
	vehicleGeofenceMapping              = queries.MakeStructMapping(vehicleGeofenceType)
	vehicleGeofencePrimaryKeyMapping, _ = queries.BindMapping(vehicleGeofenceType, vehicleGeofenceMapping, vehicleGeofencePrimaryKeyColumns)
	vehicleGeofenceInsertCacheMut       sync.RWMutex
	vehicleGeofenceInsertCache          = make(map[string]insertCache)
	vehicleGeofenceUpdateCacheMut       sync.RWMutex
	vehicleGeofenceUpdateCache          = make(map[string]updateCache)
	vehicleGeofenceUpsertCacheMut       sync.RWMutex
	vehicleGeofenceUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var vehicleGeofenceAfterSelectMu sync.Mutex
var vehicleGeofenceAfterSelectHooks []VehicleGeofenceHook

var vehicleGeofenceBeforeInsertMu sync.Mutex
var vehicleGeofenceBeforeInsertHooks []VehicleGeofenceHook
var vehicleGeofenceAfterInsertMu sync.Mutex
var vehicleGeofenceAfterInsertHooks []VehicleGeofenceHook

var vehicleGeofenceBeforeUpdateMu sync.Mutex
var vehicleGeofenceBeforeUpdateHooks []VehicleGeofenceHook
var vehicleGeofenceAfterUpdateMu sync.Mutex
var vehicleGeofenceAfterUpdateHooks []VehicleGeofenceHook

var vehicleGeofenceBeforeDeleteMu sync.Mutex
var vehicleGeofenceBeforeDeleteHooks []VehicleGeofenceHook
var vehicleGeofenceAfterDeleteMu sync.Mutex
var vehicleGeofenceAfterDeleteHooks []VehicleGeofenceHook

var vehicleGeofenceBeforeUpsertMu sync.Mutex
var vehicleGeofenceBeforeUpsertHooks []VehicleGeofenceHook
var vehicleGeofenceAfterUpsertMu sync.Mutex
var vehicleGeofenceAfterUpsertHooks []VehicleGeofenceHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *VehicleGeofence) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vehicleGeofenceAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *VehicleGeofence) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vehicleGeofenceBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *VehicleGeofence) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vehicleGeofenceAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *VehicleGeofence) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vehicleGeofenceBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *VehicleGeofence) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vehicleGeofenceAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *VehicleGeofence) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vehicleGeofenceBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *VehicleGeofence) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vehicleGeofenceAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *VehicleGeofence) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vehicleGeofenceBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *VehicleGeofence) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vehicleGeofenceAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddVehicleGeofenceHook registers your hook function for all future operations.
func AddVehicleGeofenceHook(hookPoint boil.HookPoint, vehicleGeofenceHook VehicleGeofenceHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		vehicleGeofenceAfterSelectMu.Lock()
		vehicleGeofenceAfterSelectHooks = append(vehicleGeofenceAfterSelectHooks, vehicleGeofenceHook)
		vehicleGeofenceAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		vehicleGeofenceBeforeInsertMu.Lock()
		vehicleGeofenceBeforeInsertHooks = append(vehicleGeofenceBeforeInsertHooks, vehicleGeofenceHook)
		vehicleGeofenceBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		vehicleGeofenceAfterInsertMu.Lock()
		vehicleGeofenceAfterInsertHooks = append(vehicleGeofenceAfterInsertHooks, vehicleGeofenceHook)
		vehicleGeofenceAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		vehicleGeofenceBeforeUpdateMu.Lock()
		vehicleGeofenceBeforeUpdateHooks = append(vehicleGeofenceBeforeUpdateHooks, vehicleGeofenceHook)
		vehicleGeofenceBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		vehicleGeofenceAfterUpdateMu.Lock()
		vehicleGeofenceAfterUpdateHooks = append(vehicleGeofenceAfterUpdateHooks, vehicleGeofenceHook)
		vehicleGeofenceAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		vehicleGeofenceBeforeDeleteMu.Lock()
		vehicleGeofenceBeforeDeleteHooks = append(vehicleGeofenceBeforeDeleteHooks, vehicleGeofenceHook)
		vehicleGeofenceBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		vehicleGeofenceAfterDeleteMu.Lock()
		vehicleGeofenceAfterDeleteHooks = append(vehicleGeofenceAfterDeleteHooks, vehicleGeofenceHook)
		vehicleGeofenceAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		vehicleGeofenceBeforeUpsertMu.Lock()
		vehicleGeofenceBeforeUpsertHooks = append(vehicleGeofenceBeforeUpsertHooks, vehicleGeofenceHook)
		vehicleGeofenceBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		vehicleGeofenceAfterUpsertMu.Lock()
		vehicleGeofenceAfterUpsertHooks = append(vehicleGeofenceAfterUpsertHooks, vehicleGeofenceHook)
		vehicleGeofenceAfterUpsertMu.Unlock()
	}
}

// One returns a single vehicleGeofence record from the query.
func (q vehicleGeofenceQuery) One(ctx context.Context, exec boil.ContextExecutor) (*VehicleGeofence, error) {
	o := &VehicleGeofence{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for vehicle_geofences")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all VehicleGeofence records from the query.
func (q vehicleGeofenceQuery) All(ctx context.Context, exec boil.ContextExecutor) (VehicleGeofenceSlice, error) {
	var o []*VehicleGeofence

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to VehicleGeofence slice")
	}

	if len(vehicleGeofenceAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all VehicleGeofence records in the query.
func (q vehicleGeofenceQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count vehicle_geofences rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q vehicleGeofenceQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if vehicle_geofences exists")
	}

	return count > 0, nil
}

// Geofence pointed to by the foreign key.
func (o *VehicleGeofence) Geofence(mods ...qm.QueryMod) geofenceQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.GeofenceID),
	}

	queryMods = append(queryMods, mods...)

	return Geofences(queryMods...)
}

// LoadGeofence allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (vehicleGeofenceL) LoadGeofence(ctx context.Context, e boil.ContextExecutor, singular bool, maybeVehicleGeofence any, mods queries.Applicator) error {
	var slice []*VehicleGeofence
	var object *VehicleGeofence

	if singular {
		var ok bool
		object, ok = maybeVehicleGeofence.(*VehicleGeofence)
		if !ok {
			object = new(VehicleGeofence)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeVehicleGeofence)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeVehicleGeofence))
			}
		}
	} else {
		s, ok := maybeVehicleGeofence.(*[]*VehicleGeofence)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeVehicleGeofence)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeVehicleGeofence))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &vehicleGeofenceR{}
		}
		args[object.GeofenceID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &vehicleGeofenceR{}
			}

			args[obj.GeofenceID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`geofences`),
		qm.WhereIn(`geofences.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Geofence")
	}

	var resultSlice []*Geofence
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Geofence")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for geofences")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for geofences")
	}

	if len(geofenceAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Geofence = foreign
		if foreign.R == nil {
			foreign.R = &geofenceR{}
		}
		foreign.R.VehicleGeofences = append(foreign.R.VehicleGeofences, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.GeofenceID == foreign.ID {
				local.R.Geofence = foreign
				if foreign.R == nil {
					foreign.R = &geofenceR{}
				}
				foreign.R.VehicleGeofences = append(foreign.R.VehicleGeofences, local)
				break
			}
		}
	}

	return nil
}

// SetGeofence of the vehicleGeofence to the related item.
// Sets o.R.Geofence to related.
// Adds o to related.R.VehicleGeofences.
func (o *VehicleGeofence) SetGeofence(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Geofence) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"vehicle_geofences\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"geofence_id"}),
		strmangle.WhereClause("\"", "\"", 2, vehicleGeofencePrimaryKeyColumns),
	)
	values := []any{related.ID, o.TenantID, o.TokenID, o.GeofenceID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.GeofenceID = related.ID
	if o.R == nil {
		o.R = &vehicleGeofenceR{
			Geofence: related,
		}
	} else {
		o.R.Geofence = related
	}

	if related.R == nil {
		related.R = &geofenceR{
			VehicleGeofences: VehicleGeofenceSlice{o},
		}
	} else {
		related.R.VehicleGeofences = append(related.R.VehicleGeofences, o)
	}

	return nil
}

// VehicleGeofences retrieves all the records using an executor.
func VehicleGeofences(mods ...qm.QueryMod) vehicleGeofenceQuery {
	mods = append(mods, qm.From("\"vehicle_geofences\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"vehicle_geofences\".*"})
	}

	return vehicleGeofenceQuery{q}
}

// FindVehicleGeofence retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindVehicleGeofence(ctx context.Context, exec boil.ContextExecutor, tenantID string, tokenID int64, geofenceID string, selectCols ...string) (*VehicleGeofence, error) {
	vehicleGeofenceObj := &VehicleGeofence{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"vehicle_geofences\" where \"tenant_id\"=$1 AND \"token_id\"=$2 AND \"geofence_id\"=$3", sel,
	)

	q := queries.Raw(query, tenantID, tokenID, geofenceID)

	err := q.Bind(ctx, exec, vehicleGeofenceObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from vehicle_geofences")
	}

	if err = vehicleGeofenceObj.doAfterSelectHooks(ctx, exec); err != nil {
		return vehicleGeofenceObj, err
	}

	return vehicleGeofenceObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *VehicleGeofence) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no vehicle_geofences provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(vehicleGeofenceColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	vehicleGeofenceInsertCacheMut.RLock()
	cache, cached := vehicleGeofenceInsertCache[key]
	vehicleGeofenceInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			vehicleGeofenceAllColumns,
			vehicleGeofenceColumnsWithDefault,
			vehicleGeofenceColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(vehicleGeofenceType, vehicleGeofenceMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(vehicleGeofenceType, vehicleGeofenceMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"vehicle_geofences\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"vehicle_geofences\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into vehicle_geofences")
	}

	if !cached {
		vehicleGeofenceInsertCacheMut.Lock()
		vehicleGeofenceInsertCache[key] = cache
		vehicleGeofenceInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the VehicleGeofence.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *VehicleGeofence) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	vehicleGeofenceUpdateCacheMut.RLock()
	cache, cached := vehicleGeofenceUpdateCache[key]
	vehicleGeofenceUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			vehicleGeofenceAllColumns,
			vehicleGeofencePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update vehicle_geofences, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"vehicle_geofences\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, vehicleGeofencePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(vehicleGeofenceType, vehicleGeofenceMapping, append(wl, vehicleGeofencePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update vehicle_geofences row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for vehicle_geofences")
	}

	if !cached {
		vehicleGeofenceUpdateCacheMut.Lock()
		vehicleGeofenceUpdateCache[key] = cache
		vehicleGeofenceUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q vehicleGeofenceQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for vehicle_geofences")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for vehicle_geofences")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o VehicleGeofenceSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), vehicleGeofencePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"vehicle_geofences\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, vehicleGeofencePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in vehicleGeofence slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all vehicleGeofence")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *VehicleGeofence) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no vehicle_geofences provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(vehicleGeofenceColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	vehicleGeofenceUpsertCacheMut.RLock()
	cache, cached := vehicleGeofenceUpsertCache[key]
	vehicleGeofenceUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			vehicleGeofenceAllColumns,
			vehicleGeofenceColumnsWithDefault,
			vehicleGeofenceColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			vehicleGeofenceAllColumns,
			vehicleGeofencePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert vehicle_geofences, could not build update column list")
		}

		ret := strmangle.SetComplement(vehicleGeofenceAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(vehicleGeofencePrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert vehicle_geofences, could not build conflict column list")
			}

			conflict = make([]string, len(vehicleGeofencePrimaryKeyColumns))
			copy(conflict, vehicleGeofencePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"vehicle_geofences\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(vehicleGeofenceType, vehicleGeofenceMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(vehicleGeofenceType, vehicleGeofenceMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert vehicle_geofences")
	}

	if !cached {
		vehicleGeofenceUpsertCacheMut.Lock()
		vehicleGeofenceUpsertCache[key] = cache
		vehicleGeofenceUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single VehicleGeofence record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *VehicleGeofence) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no VehicleGeofence provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), vehicleGeofencePrimaryKeyMapping)
	sql := "DELETE FROM \"vehicle_geofences\" WHERE \"tenant_id\"=$1 AND \"token_id\"=$2 AND \"geofence_id\"=$3"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from vehicle_geofences")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for vehicle_geofences")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q vehicleGeofenceQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no vehicleGeofenceQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from vehicle_geofences")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for vehicle_geofences")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o VehicleGeofenceSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(vehicleGeofenceBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), vehicleGeofencePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"vehicle_geofences\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, vehicleGeofencePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from vehicleGeofence slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for vehicle_geofences")
	}

	if len(vehicleGeofenceAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *VehicleGeofence) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindVehicleGeofence(ctx, exec, o.TenantID, o.TokenID, o.GeofenceID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *VehicleGeofenceSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := VehicleGeofenceSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), vehicleGeofencePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"vehicle_geofences\".* FROM \"vehicle_geofences\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, vehicleGeofencePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in VehicleGeofenceSlice")
	}

	*o = slice

	return nil
}

// VehicleGeofenceExists checks if the VehicleGeofence row exists.
func VehicleGeofenceExists(ctx context.Context, exec boil.ContextExecutor, tenantID string, tokenID int64, geofenceID string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"vehicle_geofences\" where \"tenant_id\"=$1 AND \"token_id\"=$2 AND \"geofence_id\"=$3 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, tenantID, tokenID, geofenceID)
	}
	row := exec.QueryRowContext(ctx, sql, tenantID, tokenID, geofenceID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if vehicle_geofences exists")
	}

	return exists, nil
}

// Exists checks if the VehicleGeofence row exists.
func (o *VehicleGeofence) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return VehicleGeofenceExists(ctx, exec, o.TenantID, o.TokenID, o.GeofenceID)
}
