// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/sqlboiler/v4/types"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// VehicleTcoSetting is an object representing the database table.
type VehicleTcoSetting struct {
	TenantID        string            `boil:"tenant_id" json:"tenant_id" toml:"tenant_id" yaml:"tenant_id"`
	TokenID         int64             `boil:"token_id" json:"token_id" toml:"token_id" yaml:"token_id"`
	PurchasePrice   types.NullDecimal `boil:"purchase_price" json:"purchase_price,omitempty" toml:"purchase_price" yaml:"purchase_price,omitempty"`
	PurchaseDate    null.Time         `boil:"purchase_date" json:"purchase_date,omitempty" toml:"purchase_date" yaml:"purchase_date,omitempty"`
	UsefulLifeYears null.Int          `boil:"useful_life_years" json:"useful_life_years,omitempty" toml:"useful_life_years" yaml:"useful_life_years,omitempty"`
	Currency        string            `boil:"currency" json:"currency" toml:"currency" yaml:"currency"`
	CreatedAt       time.Time         `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt       time.Time         `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *vehicleTcoSettingR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L vehicleTcoSettingL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var VehicleTcoSettingColumns = struct {
	TenantID        string
	TokenID         string
	PurchasePrice   string
	PurchaseDate    string
	UsefulLifeYears string
	Currency        string
	CreatedAt       string
	UpdatedAt       string
}{
	TenantID:        "tenant_id",
	TokenID:         "token_id",
	PurchasePrice:   "purchase_price",
	PurchaseDate:    "purchase_date",
	UsefulLifeYears: "useful_life_years",
	Currency:        "currency",
	CreatedAt:       "created_at",
	UpdatedAt:       "updated_at",
}

var VehicleTcoSettingTableColumns = struct {
	TenantID        string
	TokenID         string
	PurchasePrice   string
	PurchaseDate    string
	UsefulLifeYears string
	Currency        string
	CreatedAt       string
	UpdatedAt       string
}{
	TenantID:        "vehicle_tco_settings.tenant_id",
	TokenID:         "vehicle_tco_settings.token_id",
	PurchasePrice:   "vehicle_tco_settings.purchase_price",
	PurchaseDate:    "vehicle_tco_settings.purchase_date",
	UsefulLifeYears: "vehicle_tco_settings.useful_life_years",
	Currency:        "vehicle_tco_settings.currency",
	CreatedAt:       "vehicle_tco_settings.created_at",
	UpdatedAt:       "vehicle_tco_settings.updated_at",
}

// Generated where

type whereHelpertypes_NullDecimal struct{ field string }

func (w whereHelpertypes_NullDecimal) EQ(x types.NullDecimal) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpertypes_NullDecimal) NEQ(x types.NullDecimal) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpertypes_NullDecimal) LT(x types.NullDecimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertypes_NullDecimal) LTE(x types.NullDecimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertypes_NullDecimal) GT(x types.NullDecimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertypes_NullDecimal) GTE(x types.NullDecimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

func (w whereHelpertypes_NullDecimal) IsNull() qm.QueryMod { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpertypes_NullDecimal) IsNotNull() qm.QueryMod {
	return qmhelper.WhereIsNotNull(w.field)
}

var VehicleTcoSettingWhere = struct {
	TenantID        whereHelperstring
	TokenID         whereHelperint64
	PurchasePrice   whereHelpertypes_NullDecimal
	PurchaseDate    whereHelpernull_Time
	UsefulLifeYears whereHelpernull_Int
	Currency        whereHelperstring
	CreatedAt       whereHelpertime_Time
	UpdatedAt       whereHelpertime_Time
}{
	TenantID:        whereHelperstring{field: "\"vehicle_tco_settings\".\"tenant_id\""},
	TokenID:         whereHelperint64{field: "\"vehicle_tco_settings\".\"token_id\""},
	PurchasePrice:   whereHelpertypes_NullDecimal{field: "\"vehicle_tco_settings\".\"purchase_price\""},
	PurchaseDate:    whereHelpernull_Time{field: "\"vehicle_tco_settings\".\"purchase_date\""},
	UsefulLifeYears: whereHelpernull_Int{field: "\"vehicle_tco_settings\".\"useful_life_years\""},
	Currency:        whereHelperstring{field: "\"vehicle_tco_settings\".\"currency\""},
	CreatedAt:       whereHelpertime_Time{field: "\"vehicle_tco_settings\".\"created_at\""},
	UpdatedAt:       whereHelpertime_Time{field: "\"vehicle_tco_settings\".\"updated_at\""},
}

// VehicleTcoSettingRels is where relationship names are stored.
var VehicleTcoSettingRels = struct {
	Tenant string
}{
	Tenant: "Tenant",
}

// vehicleTcoSettingR is where relationships are stored.
type vehicleTcoSettingR struct {
	Tenant *Tenant `boil:"Tenant" json:"Tenant" toml:"Tenant" yaml:"Tenant"`
}

// NewStruct creates a new relationship struct
func (*vehicleTcoSettingR) NewStruct() *vehicleTcoSettingR {
	return &vehicleTcoSettingR{}
}

func (o *VehicleTcoSetting) GetTenant() *Tenant {
	if o == nil {
		return nil
	}

	return o.R.GetTenant()
}

func (r *vehicleTcoSettingR) GetTenant() *Tenant {
	if r == nil {
		return nil
	}

	return r.Tenant
}

// vehicleTcoSettingL is where Load methods for each relationship are stored.
type vehicleTcoSettingL struct{}

var (
	vehicleTcoSettingAllColumns            = []string{"tenant_id", "token_id", "purchase_price", "purchase_date", "useful_life_years", "currency", "created_at", "updated_at"}
	vehicleTcoSettingColumnsWithoutDefault = []string{"tenant_id", "token_id"}
	vehicleTcoSettingColumnsWithDefault    = []string{"purchase_price", "purchase_date", "useful_life_years", "currency", "created_at", "updated_at"}
	vehicleTcoSettingPrimaryKeyColumns     = []string{"tenant_id", "token_id"}
	vehicleTcoSettingGeneratedColumns      = []string{}
)

type (
	// VehicleTcoSettingSlice is an alias for a slice of pointers to VehicleTcoSetting.
	// This should almost always be used instead of []VehicleTcoSetting.
	VehicleTcoSettingSlice []*VehicleTcoSetting
	// VehicleTcoSettingHook is the signature for custom VehicleTcoSetting hook methods
	VehicleTcoSettingHook func(context.Context, boil.ContextExecutor, *VehicleTcoSetting) error

	vehicleTcoSettingQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	vehicleTcoSettingType                 = reflect.TypeOf(&VehicleTcoSetting{})
	vehicleTcoSettingMapping              = queries.MakeStructMapping(vehicleTcoSettingType)
	vehicleTcoSettingPrimaryKeyMapping, _ = queries.BindMapping(vehicleTcoSettingType, vehicleTcoSettingMapping, vehicleTcoSettingPrimaryKeyColumns)
	vehicleTcoSettingInsertCacheMut       sync.RWMutex
	vehicleTcoSettingInsertCache          = make(map[string]insertCache)
	vehicleTcoSettingUpdateCacheMut       sync.RWMutex
	vehicleTcoSettingUpdateCache          = make(map[string]updateCache)
	vehicleTcoSettingUpsertCacheMut       sync.RWMutex
	vehicleTcoSettingUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var vehicleTcoSettingAfterSelectMu sync.Mutex
var vehicleTcoSettingAfterSelectHooks []VehicleTcoSettingHook

var vehicleTcoSettingBeforeInsertMu sync.Mutex
var vehicleTcoSettingBeforeInsertHooks []VehicleTcoSettingHook
var vehicleTcoSettingAfterInsertMu sync.Mutex
var vehicleTcoSettingAfterInsertHooks []VehicleTcoSettingHook

var vehicleTcoSettingBeforeUpdateMu sync.Mutex
var vehicleTcoSettingBeforeUpdateHooks []VehicleTcoSettingHook
var vehicleTcoSettingAfterUpdateMu sync.Mutex
var vehicleTcoSettingAfterUpdateHooks []VehicleTcoSettingHook

var vehicleTcoSettingBeforeDeleteMu sync.Mutex
var vehicleTcoSettingBeforeDeleteHooks []VehicleTcoSettingHook
var vehicleTcoSettingAfterDeleteMu sync.Mutex
var vehicleTcoSettingAfterDeleteHooks []VehicleTcoSettingHook

var vehicleTcoSettingBeforeUpsertMu sync.Mutex
var vehicleTcoSettingBeforeUpsertHooks []VehicleTcoSettingHook
var vehicleTcoSettingAfterUpsertMu sync.Mutex
var vehicleTcoSettingAfterUpsertHooks []VehicleTcoSettingHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *VehicleTcoSetting) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vehicleTcoSettingAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *VehicleTcoSetting) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vehicleTcoSettingBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *VehicleTcoSetting) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vehicleTcoSettingAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *VehicleTcoSetting) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vehicleTcoSettingBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *VehicleTcoSetting) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vehicleTcoSettingAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *VehicleTcoSetting) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vehicleTcoSettingBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *VehicleTcoSetting) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vehicleTcoSettingAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *VehicleTcoSetting) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vehicleTcoSettingBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *VehicleTcoSetting) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vehicleTcoSettingAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddVehicleTcoSettingHook registers your hook function for all future operations.
func AddVehicleTcoSettingHook(hookPoint boil.HookPoint, vehicleTcoSettingHook VehicleTcoSettingHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		vehicleTcoSettingAfterSelectMu.Lock()
		vehicleTcoSettingAfterSelectHooks = append(vehicleTcoSettingAfterSelectHooks, vehicleTcoSettingHook)
		vehicleTcoSettingAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		vehicleTcoSettingBeforeInsertMu.Lock()
		vehicleTcoSettingBeforeInsertHooks = append(vehicleTcoSettingBeforeInsertHooks, vehicleTcoSettingHook)
		vehicleTcoSettingBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		vehicleTcoSettingAfterInsertMu.Lock()
		vehicleTcoSettingAfterInsertHooks = append(vehicleTcoSettingAfterInsertHooks, vehicleTcoSettingHook)
		vehicleTcoSettingAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		vehicleTcoSettingBeforeUpdateMu.Lock()
		vehicleTcoSettingBeforeUpdateHooks = append(vehicleTcoSettingBeforeUpdateHooks, vehicleTcoSettingHook)
		vehicleTcoSettingBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		vehicleTcoSettingAfterUpdateMu.Lock()
		vehicleTcoSettingAfterUpdateHooks = append(vehicleTcoSettingAfterUpdateHooks, vehicleTcoSettingHook)
		vehicleTcoSettingAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		vehicleTcoSettingBeforeDeleteMu.Lock()
		vehicleTcoSettingBeforeDeleteHooks = append(vehicleTcoSettingBeforeDeleteHooks, vehicleTcoSettingHook)
		vehicleTcoSettingBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		vehicleTcoSettingAfterDeleteMu.Lock()
		vehicleTcoSettingAfterDeleteHooks = append(vehicleTcoSettingAfterDeleteHooks, vehicleTcoSettingHook)
		vehicleTcoSettingAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		vehicleTcoSettingBeforeUpsertMu.Lock()
		vehicleTcoSettingBeforeUpsertHooks = append(vehicleTcoSettingBeforeUpsertHooks, vehicleTcoSettingHook)
		vehicleTcoSettingBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		vehicleTcoSettingAfterUpsertMu.Lock()
		vehicleTcoSettingAfterUpsertHooks = append(vehicleTcoSettingAfterUpsertHooks, vehicleTcoSettingHook)
		vehicleTcoSettingAfterUpsertMu.Unlock()
	}
}

// One returns a single vehicleTcoSetting record from the query.
func (q vehicleTcoSettingQuery) One(ctx context.Context, exec boil.ContextExecutor) (*VehicleTcoSetting, error) {
	o := &VehicleTcoSetting{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for vehicle_tco_settings")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all VehicleTcoSetting records from the query.
func (q vehicleTcoSettingQuery) All(ctx context.Context, exec boil.ContextExecutor) (VehicleTcoSettingSlice, error) {
	var o []*VehicleTcoSetting

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to VehicleTcoSetting slice")
	}

	if len(vehicleTcoSettingAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all VehicleTcoSetting records in the query.
func (q vehicleTcoSettingQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count vehicle_tco_settings rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q vehicleTcoSettingQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if vehicle_tco_settings exists")
	}

	return count > 0, nil
}

// Tenant pointed to by the foreign key.
func (o *VehicleTcoSetting) Tenant(mods ...qm.QueryMod) tenantQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.TenantID),
	}

	queryMods = append(queryMods, mods...)

	return Tenants(queryMods...)
}

// LoadTenant allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (vehicleTcoSettingL) LoadTenant(ctx context.Context, e boil.ContextExecutor, singular bool, maybeVehicleTcoSetting any, mods queries.Applicator) error {
	var slice []*VehicleTcoSetting
	var object *VehicleTcoSetting

	if singular {
		var ok bool
		object, ok = maybeVehicleTcoSetting.(*VehicleTcoSetting)
		if !ok {
			object = new(VehicleTcoSetting)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeVehicleTcoSetting)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeVehicleTcoSetting))
			}
		}
	} else {
		s, ok := maybeVehicleTcoSetting.(*[]*VehicleTcoSetting)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeVehicleTcoSetting)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeVehicleTcoSetting))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &vehicleTcoSettingR{}
		}
		args[object.TenantID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &vehicleTcoSettingR{}
			}

			args[obj.TenantID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`tenants`),
		qm.WhereIn(`tenants.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Tenant")
	}

	var resultSlice []*Tenant
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Tenant")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for tenants")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for tenants")
	}

	if len(tenantAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Tenant = foreign
		if foreign.R == nil {
			foreign.R = &tenantR{}
		}
		foreign.R.VehicleTcoSettings = append(foreign.R.VehicleTcoSettings, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.TenantID == foreign.ID {
				local.R.Tenant = foreign
				if foreign.R == nil {
					foreign.R = &tenantR{}
				}
				foreign.R.VehicleTcoSettings = append(foreign.R.VehicleTcoSettings, local)
				break
			}
		}
	}

	return nil
}

// SetTenant of the vehicleTcoSetting to the related item.
// Sets o.R.Tenant to related.
// Adds o to related.R.VehicleTcoSettings.
func (o *VehicleTcoSetting) SetTenant(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Tenant) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"vehicle_tco_settings\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"tenant_id"}),
		strmangle.WhereClause("\"", "\"", 2, vehicleTcoSettingPrimaryKeyColumns),
	)
	values := []any{related.ID, o.TenantID, o.TokenID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.TenantID = related.ID
	if o.R == nil {
		o.R = &vehicleTcoSettingR{
			Tenant: related,
		}
	} else {
		o.R.Tenant = related
	}

	if related.R == nil {
		related.R = &tenantR{
			VehicleTcoSettings: VehicleTcoSettingSlice{o},
		}
	} else {
		related.R.VehicleTcoSettings = append(related.R.VehicleTcoSettings, o)
	}

	return nil
}

// VehicleTcoSettings retrieves all the records using an executor.
func VehicleTcoSettings(mods ...qm.QueryMod) vehicleTcoSettingQuery {
	mods = append(mods, qm.From("\"vehicle_tco_settings\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"vehicle_tco_settings\".*"})
	}

	return vehicleTcoSettingQuery{q}
}

// FindVehicleTcoSetting retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindVehicleTcoSetting(ctx context.Context, exec boil.ContextExecutor, tenantID string, tokenID int64, selectCols ...string) (*VehicleTcoSetting, error) {
	vehicleTcoSettingObj := &VehicleTcoSetting{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"vehicle_tco_settings\" where \"tenant_id\"=$1 AND \"token_id\"=$2", sel,
	)

	q := queries.Raw(query, tenantID, tokenID)

	err := q.Bind(ctx, exec, vehicleTcoSettingObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from vehicle_tco_settings")
	}

	if err = vehicleTcoSettingObj.doAfterSelectHooks(ctx, exec); err != nil {
		return vehicleTcoSettingObj, err
	}

	return vehicleTcoSettingObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *VehicleTcoSetting) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no vehicle_tco_settings provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(vehicleTcoSettingColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	vehicleTcoSettingInsertCacheMut.RLock()
	cache, cached := vehicleTcoSettingInsertCache[key]
	vehicleTcoSettingInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			vehicleTcoSettingAllColumns,
			vehicleTcoSettingColumnsWithDefault,
			vehicleTcoSettingColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(vehicleTcoSettingType, vehicleTcoSettingMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(vehicleTcoSettingType, vehicleTcoSettingMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"vehicle_tco_settings\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"vehicle_tco_settings\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into vehicle_tco_settings")
	}

	if !cached {
		vehicleTcoSettingInsertCacheMut.Lock()
		vehicleTcoSettingInsertCache[key] = cache
		vehicleTcoSettingInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the VehicleTcoSetting.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *VehicleTcoSetting) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	vehicleTcoSettingUpdateCacheMut.RLock()
	cache, cached := vehicleTcoSettingUpdateCache[key]
	vehicleTcoSettingUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			vehicleTcoSettingAllColumns,
			vehicleTcoSettingPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update vehicle_tco_settings, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"vehicle_tco_settings\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, vehicleTcoSettingPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(vehicleTcoSettingType, vehicleTcoSettingMapping, append(wl, vehicleTcoSettingPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update vehicle_tco_settings row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for vehicle_tco_settings")
	}

	if !cached {
		vehicleTcoSettingUpdateCacheMut.Lock()
		vehicleTcoSettingUpdateCache[key] = cache
		vehicleTcoSettingUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q vehicleTcoSettingQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for vehicle_tco_settings")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for vehicle_tco_settings")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o VehicleTcoSettingSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), vehicleTcoSettingPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"vehicle_tco_settings\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, vehicleTcoSettingPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in vehicleTcoSetting slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all vehicleTcoSetting")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *VehicleTcoSetting) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no vehicle_tco_settings provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(vehicleTcoSettingColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	vehicleTcoSettingUpsertCacheMut.RLock()
	cache, cached := vehicleTcoSettingUpsertCache[key]
	vehicleTcoSettingUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			vehicleTcoSettingAllColumns,
			vehicleTcoSettingColumnsWithDefault,
			vehicleTcoSettingColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			vehicleTcoSettingAllColumns,
			vehicleTcoSettingPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert vehicle_tco_settings, could not build update column list")
		}

		ret := strmangle.SetComplement(vehicleTcoSettingAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(vehicleTcoSettingPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert vehicle_tco_settings, could not build conflict column list")
			}

			conflict = make([]string, len(vehicleTcoSettingPrimaryKeyColumns))
			copy(conflict, vehicleTcoSettingPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"vehicle_tco_settings\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(vehicleTcoSettingType, vehicleTcoSettingMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(vehicleTcoSettingType, vehicleTcoSettingMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert vehicle_tco_settings")
	}

	if !cached {
		vehicleTcoSettingUpsertCacheMut.Lock()
		vehicleTcoSettingUpsertCache[key] = cache
		vehicleTcoSettingUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single VehicleTcoSetting record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *VehicleTcoSetting) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no VehicleTcoSetting provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), vehicleTcoSettingPrimaryKeyMapping)
	sql := "DELETE FROM \"vehicle_tco_settings\" WHERE \"tenant_id\"=$1 AND \"token_id\"=$2"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from vehicle_tco_settings")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for vehicle_tco_settings")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q vehicleTcoSettingQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no vehicleTcoSettingQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from vehicle_tco_settings")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for vehicle_tco_settings")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o VehicleTcoSettingSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(vehicleTcoSettingBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), vehicleTcoSettingPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"vehicle_tco_settings\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, vehicleTcoSettingPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from vehicleTcoSetting slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for vehicle_tco_settings")
	}

	if len(vehicleTcoSettingAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *VehicleTcoSetting) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindVehicleTcoSetting(ctx, exec, o.TenantID, o.TokenID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *VehicleTcoSettingSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := VehicleTcoSettingSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), vehicleTcoSettingPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"vehicle_tco_settings\".* FROM \"vehicle_tco_settings\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, vehicleTcoSettingPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in VehicleTcoSettingSlice")
	}

	*o = slice

	return nil
}

// VehicleTcoSettingExists checks if the VehicleTcoSetting row exists.
func VehicleTcoSettingExists(ctx context.Context, exec boil.ContextExecutor, tenantID string, tokenID int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"vehicle_tco_settings\" where \"tenant_id\"=$1 AND \"token_id\"=$2 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, tenantID, tokenID)
	}
	row := exec.QueryRowContext(ctx, sql, tenantID, tokenID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if vehicle_tco_settings exists")
	}

	return exists, nil
}

// Exists checks if the VehicleTcoSetting row exists.
func (o *VehicleTcoSetting) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return VehicleTcoSettingExists(ctx, exec, o.TenantID, o.TokenID)
}
