replicaCount: 2
image:
  repository: dimozone/fleet-lite-app
  pullPolicy: IfNotPresent
  tag: 08f3588
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  annotations: {}
  name: ''
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
env:
  ENVIRONMENT: prod
  USE_DEV_CERTS: false
  API_PORT: '8084'
  MONITORING_PORT: '8085'
  LOG_LEVEL: info
  SERVICE_NAME: fleet-lite-app
  DB_PORT: '5432'
  DB_NAME: fleets_lite
  DB_MAX_OPEN_CONNECTIONS: '20'
  DB_MAX_IDLE_CONNECTIONS: '6'
  DB_SSL_MODE: require
  JWT_KEY_SET_URL: https://auth.dimo.zone/keys
  TOKEN_EXCHANGE_URL: https://token-exchange-api.dimo.zone
  DIMO_LOGIN_URL: https://login.dimo.org
  DIMO_AUTH_URL: https://auth.dimo.zone
  DIMO_AUTH_CLIENT_ID: '0x51dacC165f1306Abfbf0a6312ec96E13AAA826DB'
  DIMO_AUTH_REDIRECT_URL: https://fleets.dimo.co/login.html
  ALLOWED_ORIGINS: https://fleets.dimo.co,https://console.dimo.org
  IDENTITY_API_ENDPOINT: http://identity-api-prod.prod.svc.cluster.local:8080/query
  EXTRACT_API_URL: http://extract-prod.prod.svc.cluster.local:8000/extract
  FETCH_API_URL: http://fetch-api-prod.prod.svc.cluster.local:8080/query
  ATTEST_API_URL: http://dis-prod-attest.prod.svc.cluster.local:8080
  TELEMETRY_API_URL: http://telemetry-api-prod.prod.svc.cluster.local:8080/query
  CHAIN_ID: '137'
  VEHICLE_NFT_ADDRESS: '0xbA5738a18d83D41847dfFbDC6101d37C69c9B0cF'
  INVITATION_FROM_EMAIL: no-reply@dimo.co
  POSTMARK_INVITATION_TEMPLATE_ALIAS: fleet-invitation
  APP_BASE_URL: https://fleets.dimo.co
service:
  type: ClusterIP
  ports:
    mon-http:
      port: 8085
      targetPort: mon-http
      protocol: TCP
    http:
      port: 8084
      targetPort: http
      protocol: TCP
ports:
  - name: mon-http
    containerPort: 8085
    protocol: TCP
  - name: http
    containerPort: 8084
    protocol: TCP
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/auth-tls-secret: ingress/cf-origin-ca
    nginx.ingress.kubernetes.io/auth-tls-verify-client: 'on'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/cors-allow-origin: https://fleets.dimo.co
    external-dns.alpha.kubernetes.io/hostname: fleets.dimo.co
  hosts:
    - host: fleets.dimo.co
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 64Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
podDisruptionBudget:
  minAvailable: 1
serviceMonitor:
  enabled: true
  path: /metrics
  port: mon-http
  interval: 30s
